using BO;

namespace BlApi;

/// <summary>
/// Defines the contract for order management operations in the business logic layer.
/// </summary>
/// <remarks>
/// This interface provides methods for creating, reading, updating, and managing orders,
/// including delivery assignment, completion, cancellation, and various query operations.
/// Implementations are expected to enforce authorization rules.
/// </remarks>
public interface IOrder : IObservable
{
    /// <summary>
    /// Creates a new order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to create the order (must be a manager).</param>
    /// <param name="boOrder">The business logic order object containing order details to create.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers are authorized to create orders.
    /// The order ID is expected to be generated by the data layer.
    /// </remarks>
    void Create(int id, BO.Order boOrder);

    /// <summary>
    /// Retrieves a specific order by its unique identifier.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to retrieve.</param>
    /// <returns>
    /// A <see cref="BO.Order"/> object with complete order details including calculated fields,
    /// or null if no order with the specified ID exists.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order details.
    /// </remarks>
    BO.Order? Read(int id, int OrderId);

    /// <summary>
    /// Retrieves statistical counts of orders grouped by status.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get statistics (must be a manager).</param>
    /// <returns>
    /// An integer array containing order counts where:
    /// - First indices contain counts for each <see cref="OrderStatus"/> value
    /// - Later indices contain counts for each <see cref="ScheduleStatus"/> value
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order statistics.
    /// </remarks>
    int[] GetAllOrderStatistic(int id);

    /// <summary>
    /// Retrieves all orders from the system with optional filtering and sorting.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read orders (must be a manager).</param>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="value">The value to match for the specified filter field.</param>
    /// <param name="sort">The field to sort by, or null for default sorting by OrderStatus.</param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="BO.OrderInList"/> objects,
    /// filtered and sorted as specified.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view all orders.
    /// </remarks>
    IEnumerable<BO.OrderInList> ReadAll(int id, BO.OrderInListField? filter, object? value, BO.OrderInListField? sort);

    /// <summary>
    /// Updates an existing order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to update the order (must be a manager).</param>
    /// <param name="boOrder">The business logic order object with updated information.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlInvalidValueException">Thrown when the order contains invalid data.</exception>
    /// <remarks>
    /// Only managers can update orders.
    /// </remarks>
    void Update(int id, BO.Order boOrder);

    /// <summary>
    /// Cancels an existing order.
    /// </summary>
    /// <param name="id">The ID of the user attempting to cancel the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to cancel.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order cannot be cancelled in its current state.</exception>
    void Cancel(int id, int orderId);

    /// <summary>
    /// Marks a delivery as completed with a specific outcome.
    /// </summary>
    /// <param name="id">The ID of the user attempting to complete the delivery (must be a manager or the assigned courier).</param>
    /// <param name="courierId">The unique identifier of the courier completing the delivery.</param>
    /// <param name="orderId">The unique identifier of the order being completed.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user is neither a manager nor the assigned courier.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or delivery is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order is not in DELIVERING status.</exception>
    /// <remarks>
    /// Managers can complete any delivery. Couriers can only complete their own assigned deliveries.
    /// </remarks>
    void Deliver(int id, int courierId, int orderId);

    /// <summary>
    /// Starts a delivery by assigning a courier to an open order.
    /// </summary>
    /// <param name="id">The ID of the user attempting to start the delivery (must be a manager or the assigned courier).</param>
    /// <param name="courierId">The unique identifier of the courier to assign to the order.</param>
    /// <param name="orderId">The unique identifier of the order to assign for delivery.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user is neither a manager nor the courier being assigned.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or courier is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order is not in OPEN or REFUSED status.</exception>
    /// <remarks>
    /// Managers can assign any order to any courier. Couriers can only accept orders for themselves.
    /// </remarks>
    void StartDelivery(int id, int courierId, int orderId);

    /// <summary>
    /// Attempts to delete an order from the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to delete the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to delete.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Always thrown if deletion is not supported.</exception>
    /// <remarks>
    /// Order deletion may be unsupported in some implementations; prefer cancellation.
    /// </remarks>
    void Delete(int id, int orderId);

    /// <summary>
    /// Retrieves all completed deliveries for a specific courier with optional filtering and sorting.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get closed deliveries (must be a manager).</param>
    /// <param name="courierId">The unique identifier of the courier whose deliveries to retrieve.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">Optional field to sort the results by, or null for default sorting.</param>
    /// <returns>An enumerable of <see cref="BO.ClosedDeliveryInList"/> items.</returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    IEnumerable<BO.ClosedDeliveryInList> GetClosed(int id, int courierId, TypeOfOrder? filter, ClosedDeliveryInListField? sort);

    /// <summary>
    /// Retrieves all open orders available for a specific courier to deliver.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get open orders (must be a manager or the specified courier).</param>
    /// <param name="courierId">The unique identifier of the courier for whom to find available orders.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">Optional field to sort the results by, or null for default sorting.</param>
    /// <returns>An enumerable of <see cref="BO.OpenOrderInList"/> items.</returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user is neither a manager nor the requested courier.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the courier is not found.</exception>
    IEnumerable<BO.OpenOrderInList> GetOpen(int id, int courierId, TypeOfOrder? filter, OpenOrderInListField? sort);
}