using BO;

namespace BlApi;

/// <summary>
/// Defines the contract for order management operations in the business logic layer.
/// </summary>
/// <remarks>
/// This interface provides methods for creating, reading, updating, and managing orders,
/// including delivery assignment, completion, cancellation, and various query operations.
/// Implementations are expected to enforce authorization rules.
/// </remarks>
public interface IOrder : IObservable
{
    /// <summary>
    /// Creates a new order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to create the order (must be a manager).</param>
    /// <param name="boOrder">The business logic order object containing order details to create.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers are authorized to create orders.
    /// The order ID is expected to be generated by the data layer.
    /// </remarks>
    Task Create(int id, BO.Order boOrder);

    /// <summary>
    /// Retrieves a specific order by its unique identifier.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to retrieve.</param>
    /// <returns>
    /// A <see cref="BO.Order"/> object with complete order details including calculated fields,
    /// or null if no order with the specified ID exists.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order details.
    /// </remarks>
    Task<BO.Order?> Read(int id, int OrderId);

    /// <summary>
    /// Retrieves statistical counts of orders grouped by status.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get statistics (must be a manager).</param>
    /// <returns>
    /// An integer array containing order counts where:
    /// - First indices contain counts for each <see cref="OrderStatus"/> value
    /// - Later indices contain counts for each <see cref="ScheduleStatus"/> value
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order statistics.
    /// </remarks>
    Task <int[]> GetAllOrderStatistic(int id);

    /// <summary>
    /// Retrieves all orders from the system with optional filtering and sorting.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read orders (must be a manager).</param>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="value">The value to match for the specified filter field.</param>
    /// <param name="sort">The field to sort by, or null for default sorting by OrderStatus.</param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="BO.OrderInList"/> objects,
    /// filtered and sorted as specified.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view all orders.
    /// </remarks>IEnumerable<BO.OrderInList> ReadAll(Func<BO.OrderInList, bool>? filter = null);
    Task <IEnumerable<BO.OrderInList>> ReadAll(int id, BO.OrderInListField? filter, object? value, BO.OrderInListField? sort);

    Task<IEnumerable<BO.OrderInList>> ReadAll(int id, Func<BO.OrderInList, bool>? filter = null, BO.OrderInListField? sort = null);

    /// <summary>
    /// Updates an existing order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to update the order (must be a manager).</param>
    /// <param name="boOrder">The business logic order object with updated information.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlInvalidValueException">Thrown when the order contains invalid data.</exception>
    /// <remarks>
    /// Only managers can update orders.
    /// </remarks>
    Task Update(int id, BO.Order boOrder);

    /// <summary>
    /// Cancels an existing order.
    /// </summary>
    /// <param name="id">The ID of the user attempting to cancel the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to cancel.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order cannot be cancelled in its current state.</exception>
    Task Cancel(int id, int orderId, bool token = false);

    /// <summary>
    /// Attempts to delete an order from the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to delete the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to delete.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Always thrown if deletion is not supported.</exception>
    /// <remarks>
    /// Order deletion may be unsupported in some implementations; prefer cancellation.
    /// </remarks>
    void Delete(int id, int orderId);


}