using BO;

namespace BlApi;

/// <summary>
/// Defines the contract for order management operations in the business logic layer.
/// </summary>
/// <remarks>
/// This interface provides methods for creating, reading, updating, and managing orders,
/// including delivery assignment, completion, cancellation, and various query operations.
/// All operations include authorization checks to ensure only authorized users (managers or assigned couriers)
/// can perform specific actions.
/// </remarks>
public interface IOrder
{
    /// <summary>
    /// Creates a new order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to create the order (must be a manager).</param>
    /// <param name="boCourier">The business logic order object containing order details to create.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers are authorized to create orders. The order date is automatically set to the current system time.
    /// The order ID is auto-generated by the data layer.
    /// </remarks>
    void Create(int id, BO.Order boCourier);

    /// <summary>
    /// Retrieves a specific order by its unique identifier.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read the order (must be a manager).</param>
    /// <param name="OrderId">The unique identifier of the order to retrieve.</param>
    /// <returns>
    /// A <see cref="BO.Order"/> object with complete order details including calculated fields,
    /// or null if no order with the specified ID exists.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order details. The returned order includes enriched information
    /// such as distance calculations, delivery status, timing constraints, and associated delivery attempts.
    /// </remarks>
    BO.Order? Read(int id, int OrderId);
    
    //IEnumerable<BO.CourierInList> ReadAll(//מתודה של צפייה בכל השליחים עם אפשרות למיין ולסנן על פי קריטריונים שנבחרו
    //    BO.CourierFieldSort? sort = null,
    //    BO.CourierFieldFilter? filter = null,
    //    object? value = null);
    
    /// <summary>
    /// Retrieves statistical counts of orders grouped by status.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get statistics (must be a manager).</param>
    /// <returns>
    /// An integer array containing order counts where:
    /// - First indices contain counts for each <see cref="OrderStatus"/> value
    /// - Later indices contain counts for each <see cref="ScheduleStatus"/> value
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view order statistics. This provides a comprehensive overview
    /// of order distribution across different states and schedule statuses for dashboard and reporting purposes.
    /// </remarks>
    int[] GetAllOrderStatistic(int id);

    /// <summary>
    /// Retrieves all orders from the system with optional filtering and sorting.
    /// </summary>
    /// <param name="id">The ID of the user attempting to read orders (must be a manager).</param>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="value">The value to match for the specified filter field.</param>
    /// <param name="sort">The field to sort by, or null for default sorting by OrderStatus.</param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="BO.OrderInList"/> objects,
    /// filtered and sorted as specified.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view all orders. The method returns lightweight order representations
    /// suitable for list views, including delivery tracking, status information, and delivery attempt counts.
    /// </remarks>
    IEnumerable< BO.OrderInList >ReadAll(int id, BO.OrderInListField? filter, object? value, BO.OrderInListField? sort);

    /// <summary>
    /// Updates an existing order in the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to update the order (must be a manager).</param>
    /// <param name="boOrder">The business logic order object with updated information.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlInvalidValueException">Thrown when the order contains invalid data (e.g., invalid phone number).</exception>
    /// <remarks>
    /// Only managers can update orders. The method validates phone numbers and updates
    /// address coordinates if the address has changed using geocoding services.
    /// If geocoding fails, the existing coordinates are retained.
    /// </remarks>
    void Update(int id, BO.Order boOrder);

    /// <summary>
    /// Cancels an existing order.
    /// </summary>
    /// <param name="id">The ID of the user attempting to cancel the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to cancel.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">
    /// Thrown when the order is already completed or cancelled, or has an invalid status.
    /// </exception>
    /// <remarks>
    /// Only managers can cancel orders. Cancellation behavior depends on order status:
    /// - OPEN/REFUSED: Creates a cancellation delivery record
    /// - DELIVERING: Updates the current delivery with cancellation status
    /// - COMPLETED/CANCELLED: Cannot be cancelled (throws exception)
    /// </remarks>
    void Cancel(int id, int orderId);

    /// <summary>
    /// Marks a delivery as completed with a specific outcome.
    /// </summary>
    /// <param name="id">The ID of the user attempting to complete the delivery (must be a manager or the assigned courier).</param>
    /// <param name="courierId">The unique identifier of the courier completing the delivery.</param>
    /// <param name="orderId">The unique identifier of the order being completed.</param>
    /// <exception cref="BO.BlNoAccessException">
    /// Thrown when the user is neither a manager nor the courier assigned to the delivery.
    /// </exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or delivery is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order is not in DELIVERING status.</exception>
    /// <remarks>
    /// Managers can complete any delivery. Couriers can only complete their own assigned deliveries.
    /// Updates the delivery record with the final outcome (delivered, refused, failed, not found)
    /// and completion time, then updates the order status accordingly.
    /// </remarks>
    void Deliver(int id, int courierId, int orderId); //סגירת הזמנה כמסופקת

    /// <summary>
    /// Starts a delivery by assigning a courier to an open order.
    /// </summary>
    /// <param name="id">The ID of the user attempting to start the delivery (must be a manager or the assigned courier).</param>
    /// <param name="courierId">The unique identifier of the courier to assign to the order.</param>
    /// <param name="orderId">The unique identifier of the order to assign for delivery.</param>
    /// <exception cref="BO.BlNoAccessException">
    /// Thrown when the user is neither a manager nor the courier being assigned to the order.
    /// </exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or courier is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order is not in OPEN or REFUSED status.</exception>
    /// <remarks>
    /// Managers can assign any order to any courier. Couriers can only accept orders for themselves.
    /// Creates a new delivery record linking the courier to the order and updates the order status to DELIVERING.
    /// Only orders with OPEN or REFUSED status can be assigned.
    /// </remarks>
    void StartDelivery(int id, int courierId, int orderId);

    /// <summary>
    /// Attempts to delete an order from the system.
    /// </summary>
    /// <param name="id">The ID of the user attempting to delete the order (must be a manager).</param>
    /// <param name="orderId">The unique identifier of the order to delete.</param>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <exception cref="BO.BlDoesNotExistException">Always thrown as orders cannot be deleted in this system.</exception>
    /// <remarks>
    /// Order deletion is not permitted in this system regardless of authorization level.
    /// Orders should be cancelled instead using the <see cref="Cancel"/> method.
    /// This method exists for interface consistency but will always throw an exception.
    /// </remarks>
    void Delete(int id, int orderId);

    /// <summary>
    /// Retrieves all completed deliveries for a specific courier with optional filtering and sorting.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get closed deliveries (must be a manager).</param>
    /// <param name="courierId">The unique identifier of the courier whose deliveries to retrieve.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">Optional field to sort the results by, or null for default sorting.</param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="BO.ClosedDeliveryInList"/> objects
    /// showing delivery outcomes, distances, times, and final statuses.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">Thrown when the user does not have manager privileges.</exception>
    /// <remarks>
    /// Only managers can view closed delivery history. Returns only deliveries that have ended
    /// (with statuses like DELIVERED, REFUSED, CANCELLED, NOTFOUND, or FAILED).
    /// Results are deduplicated by OrderId to show only the most recent delivery attempt for each order.
    /// </remarks>
    IEnumerable< BO.ClosedDeliveryInList> GetClosed(int id, int courierId, TypeOfOrder? filter, ClosedDeliveryInListField? sort);

    /// <summary>
    /// Retrieves all open orders available for a specific courier to deliver.
    /// </summary>
    /// <param name="id">The ID of the user attempting to get open orders (must be a manager or the specified courier).</param>
    /// <param name="courierId">The unique identifier of the courier for whom to find available orders.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">Optional field to sort the results by, or null for default sorting.</param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="BO.OpenOrderInList"/> objects
    /// representing orders within the courier's delivery range and capability.
    /// </returns>
    /// <exception cref="BO.BlNoAccessException">
    /// Thrown when the user is neither a manager nor the courier whose orders are being requested.
    /// </exception>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the courier is not found.</exception>
    /// <remarks>
    /// Managers can view open orders for any courier. Couriers can only view their own available orders.
    /// Returns only orders with OPEN or REFUSED status that are within the courier's maximum
    /// delivery distance capability, with calculated distances, timing estimates, schedule status,
    /// and feasibility information for decision-making.
    /// </remarks>
    IEnumerable <BO.OpenOrderInList> GetOpen(int id, int courierId, TypeOfOrder? filter, OpenOrderInListField? sort);

}