<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	  <OutputPath>$(SolutionDir)\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
	  <ApplicationIcon>Images\לוגו אייקון (1).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\image_login.png" />
    <None Remove="Images\video_empty_orders.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\video_empty_orders.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Images\לוגו אייקון (1).ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\image_login.png" />
  </ItemGroup>
  
</Project>
