<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <BaseOutputPath>$(SolutionDir)\bin\</BaseOutputPath>
	  <OutputPath>$(SolutionDir)\bin\</OutputPath>
	  <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	  <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	  <UseCommonOutputDirectory>true</UseCommonOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <None Remove="NewFolder1\**" />
    <Page Remove="NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="AssemblyInfo.cs" />
    <Compile Remove="Delivery\StertDeliveryWindow.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BL\BL.csproj" />
  </ItemGroup>

</Project>
