using DalApi;
using DO;
using System;

namespace BO;
internal class Program
{
    static readonly BlApi.IBl s_bl = BlApi.Factory.Get();

    /// <summary>
    /// Prompts the user to enter an integer value from the console.
    /// </summary>
    /// <returns>A valid integer entered by the user.</returns>
    /// <remarks>
    /// This method continuously prompts the user until a valid integer is entered.
    /// If the input cannot be parsed as an integer, displays an error message and requests new input.
    /// </remarks>
    public static int GetIntInput()
    {
        int result;
        while (true)
        {
            if (int.TryParse(Console.ReadLine(), out result))
            {
                return result;
            }
            Console.WriteLine("Invalid input. Please enter a valid integer.");
        }
    }

    /// <summary>
    /// Prompts the user to enter details for creating a new courier through the console interface.
    /// </summary>
    /// <returns>A <see cref="Courier"/> object populated with user-provided information.</returns>
    /// <remarks>
    /// This method collects the following information from the user:
    /// <list type="bullet">
    /// <item><description>Courier ID</description></item>
    /// <item><description>Name</description></item>
    /// <item><description>Phone number</description></item>
    /// <item><description>Email address</description></item>
    /// <item><description>Password (required, cannot be empty)</description></item>
    /// <item><description>Type of shipment (CAR=0, MOTORCYCLE=1, BICYCLE=2, FOOT=3)</description></item>
    /// <item><description>Maximum delivery distance in kilometers</description></item>
    /// </list>
    /// The courier is automatically marked as active, and the working since date is set to the current system clock time.
    /// </remarks>
    private static Courier createCourier()
    {


        Console.WriteLine("Creating a new courier...");

        Console.Write("Enter ID of courier: ");
        int id = GetIntInput();

        Console.Write("Enter Name: ");
        string name = Console.ReadLine() ?? string.Empty;

        Console.Write("Enter Phone: ");
        string phone = Console.ReadLine() ?? string.Empty;

        Console.Write("Enter Email: ");
        string email = Console.ReadLine() ?? string.Empty;

        string password = string.Empty;
        while (password == string.Empty)
        {
            Console.Write("Enter Password: ");
            password = Console.ReadLine() ?? string.Empty;
        }

        Console.Write("Enter Type Shipment (0=CAR, 1=MOTORCYCLE, 2=BICYCLE, 3=FOOT): ");
        int typeShipmentInput = GetIntInput();

        Console.Write("Enter Max Distance Delivery (in km): ");
        string maxDistanceInput = Console.ReadLine() ?? "0";
        double maxDistanceDelivery = double.Parse(maxDistanceInput);

        return new Courier
        {
            Id = id,
            Name = name,
            Phone = phone,
            Email = email,
            Password = password,
            Active = true,
            MaxDistanceDelivery = maxDistanceDelivery,
            TypeShipment = (TheTypeShipment)typeShipmentInput,
            WorkingSince = s_bl.Admin.GetClock(),
            DeliveryOnTime = 0,
            DeliveryLate = 0,

        };

    }
    /// <summary>
    /// Prompts the user to enter details for creating a new order through the console interface.
    /// </summary>
    /// <returns>An <see cref="Order"/> object populated with user-provided information.</returns>
    /// <remarks>
    /// This method collects the following information from the user:
    /// <list type="bullet">
    /// <item><description>Type of order (STANDART=0, FAST_DELIVERY=1, DELIVER_IMMEDIATELY=2)</description></item>
    /// <item><description>Order details/description</description></item>
    /// <item><description>Delivery address</description></item>
    /// <item><description>Weight of the order in grams</description></item>
    /// <item><description>Customer name</description></item>
    /// <item><description>Customer phone number</description></item>
    /// </list>
    /// The order is automatically assigned:
    /// <list type="bullet">
    /// <item><description>ID of 0 (to be generated by the system)</description></item>
    /// <item><description>OPEN status</description></item>
    /// <item><description>ONTYME schedule status</description></item>
    /// <item><description>Order date set to current system clock time</description></item>
    /// <item><description>Estimated and maximum delivery times set to current clock time (placeholders)</description></item>
    /// </list>
    /// </remarks>
    private static Order createOrder()
    {
        Console.WriteLine("Enter type of order ( STANDART=0, FAST_DELIVERY=1,DELIVER_IMMEDIATELY=2): ");
        int typeOfOrderInput = GetIntInput();
        Console.WriteLine("Enter details of order");
        string? datails = Console.ReadLine();
        Console.WriteLine("Enter address of order: ");
        string? address = Console.ReadLine();
        Console.WriteLine("Enter weight of order (in grams): ");
        int weight = GetIntInput();
        Console.WriteLine("Enter name of customer: ");
        string? name = Console.ReadLine();
        Console.WriteLine("Enter phone of customer: ");
        string? phone = Console.ReadLine();
        return new Order
        {
            Id = 0,
            TypeOfOrder = (TypeOfOrder)typeOfOrderInput,
            Details = datails ?? string.Empty,
            Addres = address ?? string.Empty,
            Weight = weight,
            Latitude = 0,
            Longitude = 0,
            Distance = 0,
            Name = name ?? string.Empty,
            Phone = phone ?? string.Empty,
            OrderDate = s_bl.Admin.GetClock(),
            EstimatedDeliveryTime = s_bl.Admin.GetClock(),
            MaxDeliveryTime = s_bl.Admin.GetClock(),
            OrderStatus = OrderStatus.OPEN,
            ScheduleStatus = ScheduleStatus.ONTYME,
            TimeLeftForDelivery = TimeSpan.Zero,
            DeliveryPerOrderInLists = new List<DeliveryPerOrderInList>(),
        };

    }
    /// <summary>
    /// Prompts the user to filter and sort couriers, then retrieves a list of couriers based on the specified criteria.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the courier list.</param>
    /// <returns>An <see cref="IEnumerable{CourierInList}"/> containing the filtered and sorted couriers.</returns>
    /// <remarks>
    /// This method provides an interactive console interface for:
    /// <list type="bullet">
    /// <item><description>Filtering couriers by active status (active only, inactive only, or all)</description></item>
    /// <item><description>Sorting couriers by various fields (Name, Id, Phone, TypeShipment, AvailableDeliveries, or no sorting)</description></item>
    /// </list>
    /// The method displays menu options to the user and collects their choices before querying the business logic layer.
    /// </remarks>
    private static IEnumerable<CourierInList> readAllCouriers(int requesterId)
    {
        Console.WriteLine($@"
                Filter couriers:                       
                    1.Active only 
                    2. Inactive only 
                    3. All (3 or any digits...)
                        Choose");
        int filterChoice = GetIntInput();

        bool? isActive = filterChoice switch
        {
            1 => true,
            2 => false,
            3 => null,
            _ => null
        };


        Console.WriteLine($@"
                Sort couriers by:
                    1. Name
                    2. Id
                    3. Phone
                    4. TypeShipment
                    5. AvailableDeliveries
                    6. No sorting
                        Choose");

        int sortChoice = GetIntInput();


        CourierFieldSort? sort = sortChoice switch
        {
            1 => CourierFieldSort.Name,
            2 => CourierFieldSort.Id,
            3 => CourierFieldSort.Phone,
            4 => CourierFieldSort.TypeShipment,
            5 => CourierFieldSort.AvailableDeliveries,
            6 => null,
            _ => null
        };

        return s_bl.Courier.ReadAll(requesterId, isActive, sort);

    }
    /// <summary>
    /// Prompts the user to filter and sort orders, then retrieves a list of orders based on the specified criteria.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the order list.</param>
    /// <returns>
    /// An <see cref="IEnumerable{OrderInList}"/> containing the filtered and sorted orders.
    /// </returns>
    /// <remarks>
    /// This method provides an interactive console interface for:
    /// <list type="bullet">
    /// <item><description>Filtering orders by various fields (OrderId, TypeOfOrder, Distance, OrderStatus, ScheduleStatus, TimeLeftForDelivery, TotalTimeOfDelivery, DeliveryAttempts)</description></item>
    /// <item><description>Specifying filter values based on the selected field</description></item>
    /// <item><description>Sorting orders by multiple criteria (OrderId, TypeOfOrder, DistanceKm, OrderStatus, ScheduleStatus)</description></item>
    /// </list>
    /// The method displays menu options to the user and collects their choices before querying the business logic layer.
    /// </remarks>
    private static IEnumerable<OrderInList> readAllOrders(int requesterId)
    {
        Console.WriteLine($@"
                Filter orders:                       
                    1. By order id 
                    2. Type Of Order 
                    3. Distance 
                    4. OrderStatus
                    5. ScheduleStatus
                    6. Time Left For Delivery
                    7. Total Time Of Delivery
                    8.Delivery Attempts
                    9. All
                        Choose");
        int filterChoice = GetIntInput();

        BO.OrderInListField? filter = filterChoice switch
        {
            1 => OrderInListField.OrderId,
            2 => OrderInListField.TypeOfOrder,
            3 => OrderInListField.DistanceKm,
            4 => OrderInListField.OrderStatus,
            5 => OrderInListField.ScheduleStatus,
            6 => OrderInListField.TimeLeftForDelivery,
            7 => OrderInListField.TotalTimeOfDelivery,
            8 => OrderInListField.DeliveryAttempts,
            _ => null
        };

        var valueChoice = -1;
        Action action = filter switch
        {
            OrderInListField.OrderId => () =>
            {
                Console.WriteLine("Enter Order ID to filter by: ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.TypeOfOrder => () =>
            {
                Console.WriteLine("Enter Type Of Order to filter by (0=STANDART, 1=FAST_DELIVERY, 2=DELIVER_IMMEDIATELY): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.DistanceKm => () =>
            {
                Console.WriteLine("Enter Distance to filter by (in km): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.OrderStatus => () =>
            {
                Console.WriteLine("Enter Order Status to filter by (0=OPEN, 1=DELIVERING, 2=COMPLETED, 3=REFUSED, 4=CANCELLED): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.ScheduleStatus => () =>
            {
                Console.WriteLine("Enter Schedule Status to filter by (0=ONTYME, 1=AT_RISK, 2=LATE, 3=CANCELLED): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.TimeLeftForDelivery => () =>
            {
                Console.WriteLine("Enter Time Left For Delivery to filter by (in Hours): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.TotalTimeOfDelivery => () =>
            {
                Console.WriteLine("Enter Total Time Of Delivery to filter by (in Hours): ");
                valueChoice = GetIntInput();
            }
            ,
            OrderInListField.DeliveryAttempts => () =>
            {
                Console.WriteLine("Enter Delivery Attempts to filter by: ");
                valueChoice = GetIntInput();
            }
            ,
            _ => () => Console.WriteLine("Enter value to filter by: ")
        };

        action();

        Console.WriteLine($@"
                Sort orders by:
                    1. OrderId
                    2. TypeOfOrder
                    3. DistanceKm
                    4. OrderStatus
                    5. ScheduleStatus
                    6. No sorting
                        Choose");
        int sortChoice = GetIntInput();
        OrderInListField? sort = sortChoice switch
        {
            1 => OrderInListField.OrderId,
            2 => OrderInListField.TypeOfOrder,
            3 => OrderInListField.DistanceKm,
            4 => OrderInListField.OrderStatus,
            5 => OrderInListField.ScheduleStatus,
            _ => null
        };

        return s_bl.Order.ReadAll(requesterId, filter, valueChoice, sort);
    }


    /// <summary>
    /// Prompts the user to update an existing courier's information through an interactive console menu.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the update operation.</param>
    /// <returns>A <see cref="Courier"/> object with updated information.</returns>
    /// <exception cref="BlDoesNotExistException">Thrown when the courier with the specified ID does not exist.</exception>
    /// <remarks>
    /// This method allows updating the following courier properties:
    /// <list type="bullet">
    /// <item><description>Name</description></item>
    /// <item><description>Phone number</description></item>
    /// <item><description>Email address</description></item>
    /// <item><description>Password</description></item>
    /// <item><description>Active/Inactive status</description></item>
    /// <item><description>Type of shipment</description></item>
    /// <item><description>Maximum delivery distance</description></item>
    /// </list>
    /// The user can exit without making changes by pressing 0.
    /// </remarks>
    private static Courier updateCourier(int requesterId)
    {
        Console.Write("Enter ID of courier to update: ");
        int id = GetIntInput();

        var courier = s_bl.Courier.Read(requesterId, id)
            ?? throw new BlDoesNotExistException($"Courier with ID {id} does not exist.");

        Console.WriteLine(@"
    Update of courier
        to exit press 0
        to update name press 1
        to update phone press 2
        to update email press 3
        to update password press 4
        to update courier Active\NotActive press 5
        to update type shipment press 6
        to update max distance delivery press 7
            Choose");

        bool flag = true;
        while (flag)
        {
            Action action = GetIntInput() switch
            {
                0 => () =>
                {
                    Console.WriteLine("Exiting update menu.");
                    flag = false;
                    return;
                }
                ,
                1 => () =>
                {
                    Console.Write("Enter new Name: ");
                    courier.Name = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                2 => () =>
                {
                    Console.Write("Enter new Phone: ");
                    courier.Phone = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                3 => () =>
                {
                    Console.Write("Enter new Email: ");
                    courier.Email = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                4 => () =>
                {
                    Console.Write("Enter new Password: ");
                    courier.Password = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                5 => () =>
                {
                    Console.Write("Enter Active status (true 1/ false 0): ");
                    string activeInput = Console.ReadLine() ?? "1";
                    courier.Active = activeInput == "1";
                    flag = false;
                }
                ,
                6 => () =>
                {
                    Console.Write("Enter new Type Shipment (0=CAR, 1=MOTORCYCLE, 2=BICYCLE, 3=FOOT): ");
                    int typeShipmentInput = GetIntInput();
                    courier.TypeShipment = (TheTypeShipment)typeShipmentInput;
                    flag = false;
                }
                ,
                7 => () =>
                {
                    Console.Write("Enter new Max Distance Delivery (in km): ");
                    string maxDistanceInput = Console.ReadLine() ?? "0";
                    courier.MaxDistanceDelivery = double.Parse(maxDistanceInput);
                    flag = false;
                }
                ,
                _ => () => Console.WriteLine("Invalid choice, please try again.")
            };

            action();
        }

        return new Courier
        {
            Id = courier.Id,
            Name = courier.Name,
            Phone = courier.Phone,
            Email = courier.Email,
            Password = courier.Password,
            Active = courier.Active,
            MaxDistanceDelivery = courier.MaxDistanceDelivery,
            TypeShipment = courier.TypeShipment,
            WorkingSince = courier.WorkingSince,
            DeliveryOnTime = courier.DeliveryOnTime,
            DeliveryLate = courier.DeliveryLate,
        };

    }
    /// <summary>
    /// Prompts the user to update an existing order's information through an interactive console menu.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the update operation.</param>
    /// <returns>An <see cref="Order"/> object with updated information.</returns>
    /// <exception cref="BlDoesNotExistException">Thrown when the order with the specified ID does not exist.</exception>
    /// <remarks>
    /// This method allows updating the following order properties:
    /// <list type="bullet">
    /// <item><description>Type of order (STANDART, FAST_DELIVERY, DELIVER_IMMEDIATELY)</description></item>
    /// <item><description>Order details/description</description></item>
    /// <item><description>Delivery address</description></item>
    /// <item><description>Weight in kilograms</description></item>
    /// <item><description>Customer name</description></item>
    /// <item><description>Customer phone number</description></item>
    /// </list>
    /// The user can exit without making changes by pressing 0.
    /// Other order properties (dates, status, etc.) are preserved from the original order.
    /// </remarks>
    private static Order updateOrder(int requesterId)
    {
        Console.Write("Enter ID of order to update: ");
        int id = GetIntInput();

        var order = s_bl.Order.Read(requesterId, id)
            ?? throw new BlDoesNotExistException($"Order with ID {id} does not exist.");

        Console.WriteLine(@"
    Update of order
        to exit press 0
        to update type of order press 1
        to update details press 2
        to update address press 3
        to update weight press 4
        to update name press 5
        to update phone press 6
            Choose");
        
        bool flag = true;
        while (flag) {
            Action action = GetIntInput() switch
            {
                0 => () =>
                {
                    Console.WriteLine("Exiting update menu.");
                    flag = false;
                    return;
                }
                ,
                1 => () =>
                {
                    Console.Write("Enter new type of order ( STANDART=0, FAST_DELIVERY=1,DELIVER_IMMEDIATELY=2): ");
                    int typeOfOrderInput = GetIntInput();
                    order.TypeOfOrder = (TypeOfOrder)typeOfOrderInput;
                    flag = false;
                }
                ,
                2 => () =>
                {
                    Console.Write("Enter new details of order: ");
                    order.Details = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                3 => () =>
                {
                    Console.Write("Enter new address of order: ");
                    order.Addres = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                4 => () =>
                {
                    Console.Write("Enter new weight of order (in kg): ");
                    order.Weight = GetIntInput();
                    flag = false;
                }
                ,
                5 => () =>
                {
                    Console.Write("Enter new name of customer: ");
                    order.Name = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                6 => () =>
                {
                    Console.Write("Enter new phone of customer: ");
                    order.Phone = Console.ReadLine() ?? string.Empty;
                    flag = false;
                }
                ,
                _ => () => Console.WriteLine("Invalid choice, please try again.")
            };

            action();
        }
        return new Order
        {
            Id = order.Id,
            TypeOfOrder = order.TypeOfOrder,
            Details = order.Details ?? string.Empty,
            Addres = order.Addres ?? string.Empty,
            Weight = order.Weight,
            Name = order.Name ?? string.Empty,
            Phone = order.Phone ?? string.Empty,
            OrderDate = order.OrderDate,
            EstimatedDeliveryTime = order.EstimatedDeliveryTime,
            MaxDeliveryTime = order.MaxDeliveryTime,
            OrderStatus = order.OrderStatus,
            ScheduleStatus = order.ScheduleStatus,
            TimeLeftForDelivery = order.TimeLeftForDelivery,
            DeliveryPerOrderInLists = order.DeliveryPerOrderInLists,
        };
    }
    /// <summary>
    /// Prompts the user to filter and sort closed deliveries for a specific courier, then retrieves the list.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the delivery list.</param>
    /// <returns>An <see cref="IEnumerable{ClosedDeliveryInList}"/> containing the filtered and sorted closed deliveries.</returns>
    /// <remarks>
    /// This method provides an interactive console interface for:
    /// <list type="bullet">
    /// <item><description>Specifying a courier ID to view their closed deliveries</description></item>
    /// <item><description>Filtering deliveries by order type (STANDART, FAST_DELIVERY, DELIVER_IMMEDIATELY, or all)</description></item>
    /// <item><description>Sorting deliveries by various fields (DeliveryId, OrderId, TypeOfOrder, Address, ShipmentType, ActualDistance, DeliveryTime, EndDelivery, or no sorting)</description></item>
    /// </list>
    /// The method displays menu options to the user and collects their choices before querying the business logic layer.
    /// </remarks>
    private static IEnumerable<ClosedDeliveryInList> getlistClosedDeliveries(int requesterId)
    {
        Console.WriteLine("Enter courier id");
        int courierId = GetIntInput();
        Console.WriteLine($@"
                Filter type of order:
                    1. STANDART only
                    2. FAST_DELIVERY only
                    3. DELIVER_IMMEDIATELY only
                        Choose");
        int filterChoice = GetIntInput();
        TypeOfOrder? typeOfOrder = filterChoice switch
        {
            1 => TypeOfOrder.STANDART,
            2 => TypeOfOrder.FAST_DELIVERY,
            3 => TypeOfOrder.DELIVER_IMMEDIATELY,
            _ => null
        };

        Console.WriteLine($@"
                Sort closed deliveries by:
                    1. DeliveryId
                    2. OrderId
                    3. TypeOfOrder
                    4. Address
                    5. ShipmentType
                    6. AqualDistens
                    7. DelyveryTime
                    8. EndDelivery
                    9. No sorting
                        Choose");
        int sortChoice = GetIntInput();
        ClosedDeliveryInListField? sort = sortChoice switch
        {
            1 => ClosedDeliveryInListField.DeliveryId,
            2 => ClosedDeliveryInListField.OrderId,
            3 => ClosedDeliveryInListField.TypeOfOrder,
            4 => ClosedDeliveryInListField.Address,
            5 => ClosedDeliveryInListField.ShipmentType,
            6 => ClosedDeliveryInListField.AqualDistens,
            7 => ClosedDeliveryInListField.DelyveryTime,
            8 => ClosedDeliveryInListField.EndDelivery,
            9 => null,
            _ => null
        };
        return s_bl.Order.GetClosed(requesterId, courierId, typeOfOrder, sort);
    }
    /// <summary>
    /// Prompts the user to filter and sort open orders available for a specific courier, then retrieves the list.
    /// </summary>
    /// <param name="requesterId">The unique identifier of the user requesting the order list.</param>
    /// <returns>An <see cref="IEnumerable{OpenOrderInList}"/> containing the filtered and sorted open orders.</returns>
    /// <remarks>
    /// This method provides an interactive console interface for:
    /// <list type="bullet">
    /// <item><description>Specifying a courier ID to view orders available for them</description></item>
    /// <item><description>Filtering orders by order type (STANDART, FAST_DELIVERY, DELIVER_IMMEDIATELY, or all)</description></item>
    /// <item><description>Sorting orders by various fields (OrderId, TypeOfOrder, DistanceKm, Weight, ScheduleStatus, or no sorting)</description></item>
    /// </list>
    /// The method displays menu options to the user and collects their choices before querying the business logic layer.
    /// Only orders that are open and within the courier's delivery range are returned.
    /// </remarks>
    private static IEnumerable<OpenOrderInList> getlistOpenOrders(int requesterId)
    {
        Console.WriteLine("Enter courier id");
        int courierId = GetIntInput();
        Console.WriteLine($@"
                Filter type of order:
                    1. STANDART only
                    2. FAST_DELIVERY only
                    3. DELIVER_IMMEDIATELY only
                        Choose");
        int filterChoice = GetIntInput();
        TypeOfOrder? typeOfOrder = filterChoice switch
        {
            1 => TypeOfOrder.STANDART,
            2 => TypeOfOrder.FAST_DELIVERY,
            3 => TypeOfOrder.DELIVER_IMMEDIATELY,
            _ => null
        };
        Console.WriteLine($@"
                Sort open orders by:
                    1. OrderId
                    2. TypeOfOrder
                    3. DistanceKm
                    4. OrderStatus
                    5. ScheduleStatus
                    6. No sorting
                        Choose");
        int sortChoice = GetIntInput();
        OpenOrderInListField? sort = sortChoice switch
        {
            1 => OpenOrderInListField.OrderId,
            2 => OpenOrderInListField.TypeOfOrder,
            3 => OpenOrderInListField.DistanceKm,
            4 => OpenOrderInListField.Weight,
            5 => OpenOrderInListField.ScheduleStatus,
            6 => null,
            _ => null
        };
        return s_bl.Order.GetOpen(requesterId, courierId, typeOfOrder, sort);
    }
    /// <summary>
    /// Prompts the user to enter new system configuration values through the console interface.
    /// </summary>
    /// <returns>A <see cref="Config"/> object populated with user-provided configuration settings.</returns>
    /// <remarks>
    /// This method collects the following configuration parameters:
    /// <list type="bullet">
    /// <item><description>Manager password</description></item>
    /// <item><description>Store address</description></item>
    /// <item><description>Maximum delivery range in kilometers</description></item>
    /// <item><description>Average speed for bike deliveries in km/h</description></item>
    /// <item><description>Average speed for car deliveries in km/h</description></item>
    /// <item><description>Average speed for foot deliveries in km/h</description></item>
    /// <item><description>Average speed for motorcycle deliveries in km/h</description></item>
    /// <item><description>Maximum delivery time in hours</description></item>
    /// <item><description>Risk range in minutes (time buffer before considered at risk)</description></item>
    /// <item><description>Maximum time of inactivity in minutes</description></item>
    /// </list>
    /// The ManagerId is set to 0 (placeholder), and Latitude/Longitude are set to 0 (to be geocoded later).
    /// </remarks>
    private static Config createConfig()
    {
        Console.WriteLine("enter new password");
        string passwordManager = Console.ReadLine() ?? string.Empty;
        Console.WriteLine("enter new store address");
        string storeAddress = Console.ReadLine() ?? string.Empty;
        Console.WriteLine("enter new max delivery range (in km)");
        double maxDeliveryRange = double.Parse(Console.ReadLine() ?? "0");
        Console.WriteLine("enter new average speed bike (in km/h)");
        double avgSpeedBike = double.Parse(Console.ReadLine() ?? "0");
        Console.WriteLine("enter new average speed car (in km/h)");
        double avgSpeedCar = double.Parse(Console.ReadLine() ?? "0");
        Console.WriteLine("enter new average speed foot (in km/h)");
        double avgSpeedFoot = double.Parse(Console.ReadLine() ?? "0");
        Console.WriteLine("enter new average speed motorcycle (in km/h)");
        double avgSpeedMotorcycle = double.Parse(Console.ReadLine() ?? "0");
        Console.WriteLine("enter new max delivery time (in hours)");
        TimeSpan maxDeliveryTime = TimeSpan.FromHours(double.Parse(Console.ReadLine() ?? "0"));
        Console.WriteLine("enter new risk range (in minutes)");
        TimeSpan riskRange = TimeSpan.FromMinutes(double.Parse(Console.ReadLine() ?? "0"));
        Console.WriteLine("enter new max time inactivity (in minutes)");
        TimeSpan maxTimeInactivity = TimeSpan.FromMinutes(double.Parse(Console.ReadLine() ?? "0"));


        return new Config()
        {
            ManagerId = 0,
            PasswordManager = passwordManager,
            StoreAddress = storeAddress,
            Latitude = 0,
            Longitude = 0,
            MaxDeliveryRange = maxDeliveryRange,
            AvgSpeedBike = avgSpeedBike,
            AvgSpeedCar = avgSpeedCar,
            AvgSpeedFoot = avgSpeedFoot,
            AvgSpeedMotorcycle = avgSpeedMotorcycle,
            MaxDeliveryTime = maxDeliveryTime,
            RiskRange = riskRange,
            MaxTimeInactivity = maxTimeInactivity,
        };
    }

    /// <summary>
    /// Displays an interactive console menu for managing couriers (CRUD operations).
    /// </summary>
    /// <remarks>
    /// This method provides a menu-driven interface with the following options:
    /// <list type="bullet">
    /// <item><description>Create a new courier</description></item>
    /// <item><description>Read/view a specific courier by ID</description></item>
    /// <item><description>Read/view all couriers with filtering and sorting options</description></item>
    /// <item><description>Update an existing courier's information</description></item>
    /// <item><description>Delete a courier by ID</description></item>
    /// <item><description>Exit the courier management menu</description></item>
    /// </list>
    /// The method uses the manager ID as the requester for all operations.
    /// All exceptions are caught and displayed to the console error stream.
    /// The menu loops until the user chooses to exit (option 0).
    /// </remarks>
    private static void setCourier()
    {
        Console.WriteLine("Set Courier Menu.");
        int requesterId = s_bl.Admin.GetConfig().ManagerId;
        int choice;
        do
        {

            Console.WriteLine(@$"

    to exit press 0
    to create courier press 1
    to read courier press 2
    to read all couriers press 3
    to update courier press 4
    to delete courier press 5
");
            choice = GetIntInput();

            try
            {
                switch (choice)
                {
                    case 0:
                        Console.WriteLine("exit from set courier");
                        break;
                    case 1:
                        Courier newCourier = createCourier();
                        s_bl.Courier.Create(requesterId, newCourier);
                        Console.WriteLine("Courier created successfully!");
                        break;
                    case 2:
                        Console.WriteLine("Enter courier id: ");
                        int id = GetIntInput();
                        Courier? result = s_bl.Courier.Read(requesterId, id);
                        Console.WriteLine(result);
                        break;

                    case 3:
                        IEnumerable<CourierInList> couriers = readAllCouriers(requesterId);

                        if (!couriers.Any())
                        {
                            Console.WriteLine("No couriers found.");
                        }
                        else
                        {
                            foreach (CourierInList courier in couriers)
                                Console.WriteLine(courier);
                        }
                        break;

                    case 4:
                        Courier updatedCourier = updateCourier(requesterId);
                        s_bl.Courier.Update(requesterId, updatedCourier);
                        break;
                    case 5:
                        Console.WriteLine("Enter courier id: ");
                        int deleteId = GetIntInput();
                        s_bl.Courier.Delete(requesterId, deleteId);
                        Console.WriteLine("Courier deleted successfully!");
                        break;
                    default:
                        Console.WriteLine("Invalid choice, please try again.");
                        break;
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex);
            }
        } while (choice != 0);
    }


    /// <summary>
    /// Displays an interactive console menu for managing orders and deliveries.
    /// </summary>
    /// <remarks>
    /// This method provides a menu-driven interface with the following options:
    /// <list type="bullet">
    /// <item><description>Create a new order</description></item>
    /// <item><description>Read/view a specific order by ID</description></item>
    /// <item><description>Read/view all orders with filtering and sorting options</description></item>
    /// <item><description>Update an existing order's information</description></item>
    /// <item><description>Delete an order by ID</description></item>
    /// <item><description>Cancel an order</description></item>
    /// <item><description>Report a delivery as completed</description></item>
    /// <item><description>Start a delivery (assign courier to order)</description></item>
    /// <item><description>View closed deliveries for a courier</description></item>
    /// <item><description>View open orders available for a courier</description></item>
    /// <item><description>Exit the order management menu</description></item>
    /// </list>
    /// The method uses the manager ID as the requester for all operations.
    /// All exceptions are caught and displayed to the console error stream.
    /// The menu loops until the user chooses to exit (option 0).
    /// </remarks>
    private static void setOrder()
    {
        Console.WriteLine("Set Order Menu.");
        int requesterId = s_bl.Admin.GetConfig().ManagerId;
        int choice;
        do
        {
            Console.WriteLine(@$"
    to exit press 0
    to create order press 1
    to read order press 2
    to read all orders press 3
    to update order press 4
    to delete order press 5
    to cancel order press 6
    To report a delivery press 7
    to start delivery press 8
    to get closed deliveries press 9
    to get open deliveries press 10
");
            choice = GetIntInput();
            try
            {
                switch (choice)
                {
                    case 0:
                        Console.WriteLine("exit from set courier");
                        break;
                    case 1:
                        Order newOrder = createOrder();
                        s_bl.Order.Create(requesterId, newOrder);
                        Console.WriteLine("Order created successfully!");
                        break;
                    case 2:
                        Console.WriteLine("Enter order id: ");
                        int id = GetIntInput();
                        Order result = s_bl.Order.Read(requesterId, id)
                            ?? throw new BlDoesNotExistException("$\"Ordr with ID {id} does not exist.\"");
                        Console.WriteLine(result);
                        break;
                    case 3:
                        IEnumerable<OrderInList> orders = readAllOrders(requesterId);
                        if (!orders.Any())
                        {
                            Console.WriteLine("No orders found.");
                        }
                        else
                        {
                            foreach (OrderInList order in orders)
                                Console.WriteLine(order);
                        }
                        break;
                    case 4:
                        Order updatedOrder = updateOrder(requesterId);
                        s_bl.Order.Update(requesterId, updatedOrder);
                        break;
                    case 5:
                        Console.WriteLine("Enter order id: ");
                        int deleteId = GetIntInput();
                        s_bl.Order.Delete(requesterId, deleteId);
                        Console.WriteLine("Order deleted successfully!");
                        break;
                    case 6:
                        Console.WriteLine("Enter order id to cancel: ");
                        int cancelId = GetIntInput();
                        s_bl.Order.Cancel(requesterId, cancelId);
                        Console.WriteLine("Order canceled successfully!");
                        break;
                    case 7:
                        Console.WriteLine("Enter delivery id to report: ");
                        int orderId = GetIntInput();
                        Console.WriteLine("Enter courier id");
                        int courierId = GetIntInput();
                        s_bl.Order.Deliver(requesterId, courierId, orderId);
                        Console.WriteLine("Delivery reported successfully!");
                        break;
                    case 8:
                        Console.WriteLine("Enter order id to start delivery: ");
                        orderId = GetIntInput();
                        Console.WriteLine("Enter courier id");
                        courierId = GetIntInput();
                        s_bl.Order.StartDelivery(requesterId, courierId, orderId);
                        Console.WriteLine("Delivery started successfully!");
                        break;
                    case 9:

                        IEnumerable<ClosedDeliveryInList> closedDeliveryInLists = getlistClosedDeliveries(requesterId);
                        if (!closedDeliveryInLists.Any())
                        {
                            Console.WriteLine("No closed deliveries found.");
                        }
                        else
                        {
                            foreach (ClosedDeliveryInList closedDelivery in closedDeliveryInLists)
                                Console.WriteLine(closedDelivery);
                        }
                        break;
                    case 10:
                        IEnumerable<OpenOrderInList> openOrderInLists = getlistOpenOrders(requesterId);
                        if (!openOrderInLists.Any())
                        {
                            Console.WriteLine("No open orders found.");
                        }
                        else
                        {
                            foreach (OpenOrderInList openOrder in openOrderInLists)
                                Console.WriteLine(openOrder);
                        }
                        break;


                }

            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex);
            }
        } while (choice != 0);


    }
    /// <summary>
    /// Displays an interactive console menu for managing system administration settings and operations.
    /// </summary>
    /// <remarks>
    /// This method provides a menu-driven interface with the following options:
    /// <list type="bullet">
    /// <item><description>Reset all data and settings to defaults</description></item>
    /// <item><description>Initialize the database with sample data</description></item>
    /// <item><description>Get the current system clock time</description></item>
    /// <item><description>Forward the system clock by a specified time unit (minutes, hours, days, weeks, months, years)</description></item>
    /// <item><description>View current configuration settings</description></item>
    /// <item><description>Update configuration settings</description></item>
    /// <item><description>Exit the admin menu</description></item>
    /// </list>
    /// All exceptions are caught and displayed to the console error stream.
    /// The menu loops until the user chooses to exit (option 0).
    /// </remarks>
    private static void setAdmin()
    {
        Console.WriteLine("Set Admin Menu.");
        int choice;
        do
        {
            Console.WriteLine(@$"
    to exit press 0
    to reset all data and settings press 1
    to initialize all data press 2
    to get clock press 3
    to forward clock press 4
    to get config values press 5
    to set config press 6

");
            choice = GetIntInput();
            try
            {
                switch (choice)
                {
                    case 0:
                        Console.WriteLine("exit from set admin");
                        break;
                    case 1:
                        s_bl.Admin.ResetDB();
                        Console.WriteLine("All data and settings have been reset successfully!");
                        break;
                    case 2:
                        s_bl.Admin.InitializeDB();
                        Console.WriteLine("All data have been initialized successfully!");
                        break;
                    case 3:
                        DateTime currentTime = s_bl.Admin.GetClock();
                        Console.WriteLine($"Current system clock time: {currentTime}");
                        break;
                    case 4:
                        Console.WriteLine("Enter unit of time to forward the clock: ");
                        Console.WriteLine($@"
                        to forward by minutes press 0
                        to forward by hours press 1
                        to forward by days press 2
                        to forward by weeks press 3
                        to forward by months press 4
                        to forward by years press 5
");
                        int unitChoice = GetIntInput();
                        if (!Enum.IsDefined(typeof(TimeUnit), unitChoice))
                        {
                            throw new BlInvalidValueException("value to forward time yunit is not valid");
                        }
                        TimeUnit unit = (TimeUnit)unitChoice;
                        s_bl.Admin.ForwardClock(unit);
                        Console.WriteLine($"System clock has been forwarded by {unit}  successfully!");
                        break;
                    case 5:
                        Config config = s_bl.Admin.GetConfig();
                        Console.WriteLine("print config");
                        if (config is null)
                        {
                            Console.WriteLine("Config is not initialized");
                        }
                        else
                        {
                            Console.WriteLine(config);
                        }
                        break;
                    case 6:
                        config = createConfig();
                        s_bl.Admin.SetConfig(config);
                        Console.WriteLine("Configuration settings have been initialized.");
                        break;
                    
                    default:
                        Console.WriteLine("Invalid choice, please try again.");
                        break;
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex);
            }

        } while (choice != 0);
    }


    //private static void dataMenu<T>(ICrud<T>? dal) where T : class
    //{
    //    string typeName = typeof(T).Name.ToLower();
    //    Console.WriteLine($"Set {typeName} Menu.");
    //    int choice;
    //    do
    //    {
    //        Console.WriteLine(@$"
    //Set {typeName} menu.
    //    to exit press 0
    //    to create {typeName} press 1
    //    to read {typeName} press 2
    //    to read all {typeName}s press 3
    //    to update press 4
    //    to delete {typeName} press 5
    //    to delete all {typeName}s press 6
    //    ");

    //        choice = GetIntInput();

    //        try
    //        {
    //            Action action = choice switch
    //            {
    //                0 => () => Console.WriteLine($"exit from set {typeof(T).Name}"),
    //                1 => () =>
    //                {
    //                    T? newItem = typeof(T).Name switch
    //                    {
    //                        nameof(Courier) => createCourier() as T,
    //                        nameof(Order) => createOrder() as T,
    //                        nameof(Delivery) => createDelivery() as T,
    //                        _ => throw new DalErrorConfig($"Unknown type: {typeof(T).Name}")
    //                    };

    //                    if (newItem != null)
    //                    {
    //                        dal?.Create(newItem);
    //                        Console.WriteLine($"{typeName} created successfully!");
    //                    }
    //                }
    //                ,
    //                2 => () =>
    //                {
    //                    Console.WriteLine($"Enter {typeName} id: ");
    //                    int id = GetIntInput();
    //                    var result = dal?.Read(id);
    //                    if (result == null)
    //                        Console.WriteLine($"No {typeName} found with id {id}");
    //                    else
    //                        Console.WriteLine(result);
    //                }
    //                ,
    //                3 => () =>
    //                {
    //                    var items = dal?.ReadAll();

    //                    if (items == null || !items.Any())
    //                    {
    //                        Console.WriteLine($"No {typeName}s found.");
    //                    }
    //                    else
    //                    {
    //                        items.ToList().ForEach(item => Console.WriteLine(item));
    //                    }
    //                }
    //                ,
    //                4 => () =>
    //                {
    //                    Console.WriteLine($"Enter {typeName} id to update: ");
    //                    int id = GetIntInput();
    //                    switch (typeof(T).Name)
    //                    {
    //                        case nameof(Courier):
    //                            updateCourier(id);
    //                            break;
    //                        case nameof(Order):
    //                            updateOrder(id);
    //                            break;
    //                        default:
    //                            throw new DalErrorConfig($"Update not supported for type: {typeof(T).Name}");
    //                    }
    //                }
    //                ,
    //                5 => () =>
    //                {
    //                    Console.WriteLine($"Enter {typeName} id: ");
    //                    int id = GetIntInput();
    //                    try
    //                    {
    //                        dal?.Delete(id);
    //                        Console.WriteLine($"{typeName} deleted successfully!");
    //                    }
    //                    catch (Exception ex)
    //                    {
    //                        Console.Error.WriteLine(ex);
    //                    }
    //                }
    //                ,
    //                6 => () =>
    //                {
    //                    dal?.DeleteAll();
    //                    Console.WriteLine($"All {typeName}s deleted successfully!");
    //                }
    //                ,
    //                _ => () => Console.WriteLine("Invalid choice, please try again.")
    //            };

    //            action();
    //        }
    //        catch (Exception ex)
    //        {
    //            Console.Error.WriteLine(ex);
    //        }
    //    } while (choice != 0);
    //}
    /// <summary>
    /// The main entry point for the BlTest console application.
    /// </summary>
    /// <remarks>
    /// This method displays the main menu with options to:
    /// <list type="bullet">
    /// <item><description>Manage couriers (option 1)</description></item>
    /// <item><description>Manage orders (option 2)</description></item>
    /// <item><description>Manage deliveries (option 3) - not implemented in stage 4</description></item>
    /// <item><description>Manage admin settings (option 5)</description></item>
    /// <item><description>Print all data (option 6) - not relevant in stage 4</description></item>
    /// <item><description>Exit the application (option 0)</description></item>
    /// </list>
    /// The application is designed for testing the Business Logic layer (BL) of the delivery system.
    /// All user interactions are through console input/output.
    /// Exceptions are caught and displayed to the console error stream.
    /// The main loop continues until the user chooses to exit.
    /// </remarks>
    static void Main()
    {
        Console.WriteLine("Hello, Book Soop! (stage 4)");
        int choice;
        do
        {
            Console.WriteLine("" +
                "Main Menu \n" +
                "   to exit press 0\n" +
                "   to set courier press 1\n" +
                "   to set order press 2\n" +
                //"   to set delivery press 3\n" +
                "   to set admin settings press 5\n" +
                "   ***no relevant in stage 4 ***to print all data press 6\n" +
                "       enter your choice: ");
            choice = GetIntInput();
            try
            {
                switch (choice)
                {
                    case 0:
                        Console.WriteLine("good bye");
                        break;
                    case 1:
                        setCourier();
                        break;
                    case 2:
                        setOrder();
                        //dataMenu(s_dal!.Order!);
                        break;
                    case 3:
                        //dataMenu(s_dal!.Delivery!);
                        break;
                    case 5:
                        setAdmin();
                        break;
                    case 6:
                        //var couriers = s_dal!.Courier?.ReadAll();
                        //if (!couriers!.Any())
                        //    Console.WriteLine("No couriers found.");

                        //else
                        //    foreach (var courier in couriers!)
                        //        Console.WriteLine(courier);


                        //var orders = s_dal!.Order?.ReadAll();
                        //if (!orders!.Any())
                        //    Console.WriteLine("No orders found");
                        //else
                        //    foreach (var order in orders!)
                        //        Console.WriteLine(order);


                        //var deliveries = s_dal!.Delivery?.ReadAll();
                        //if (!deliveries!.Any())
                        //    Console.WriteLine("No deliveries found");
                        //else

                        //    foreach (var delivery in deliveries!)
                        //        Console.WriteLine(delivery);


                        break;
                    //case 7:
                    //    settingMenu();
                    //    break;
                    //case 8:
                    //    Console.WriteLine("Delete all data.");
                    //    s_dal!.Config?.Reset();
                    //    s_dal!.Delivery?.DeleteAll();
                    //    s_dal!.Order?.DeleteAll();
                    //    s_dal!.Courier?.DeleteAll();
                    //    break;
                    default:
                        Console.WriteLine("Please enter one of the following options: ");
                        break;
                }
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine(ex);
            }
        } while (choice != 0);
    }
}

