using DalApi;

namespace Helpers;

/// <summary>
/// Manages delivery-related operations in the business logic layer.
/// </summary>
/// <remarks>
/// This static class provides functionality for creating, reading, and managing deliveries.
/// It acts as an intermediary between the business logic layer and the data access layer,
/// handling delivery lifecycle operations including creation, retrieval, and completion.
/// </remarks>
internal static class DeliveryManager
{
    /// <summary>
    /// Data access layer instance for database operations.
    /// </summary>
    private static readonly IDal s_dal = Factory.Get;

    /// <summary>
    /// Observer manager for notifying UI components about delivery changes.
    /// </summary>
    internal static readonly ObserverManager Observer = new();

    /// <summary>
    /// Retrieves all deliveries from the data access layer.
    /// </summary>
    /// <param name="sort">
    /// Optional sorting criterion for deliveries. 
    /// Currently not implemented - parameter is ignored.
    /// </param>
    /// <returns>
    /// An <see cref="IEnumerable{T}"/> of <see cref="DO.Delivery"/> objects 
    /// representing all deliveries in the system.
    /// </returns>
    /// <remarks>
    /// Note: The sort parameter is currently not utilized in the implementation.
    /// All deliveries are returned in their default order from the data access layer.
    /// </remarks>
    internal static IEnumerable<DO.Delivery> ReadAll(BO.CourierFieldSort? sort = BO.CourierFieldSort.Id)
    {
        return s_dal.Delivery.ReadAll();
    }

    /// <summary>
    /// Retrieves a specific delivery by its unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the delivery to retrieve.</param>
    /// <returns>
    /// The <see cref="DO.Delivery"/> object with the specified ID, 
    /// or null if not found.
    /// </returns>
    internal static DO.Delivery? Read(int id)
    {
        return s_dal.Delivery.Read(id);
    }

    /// <summary>
    /// Creates a new delivery assignment for a specific order and courier.
    /// </summary>
    /// <param name="order">The <see cref="DO.Order"/> to be delivered.</param>
    /// <param name="courier">The <see cref="DO.Courier"/> assigned to deliver the order.</param>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when the order's delivery distance exceeds the courier's maximum delivery distance capability.
    /// </exception>
    /// <remarks>
    /// This method performs the following operations:
    /// <list type="number">
    ///   <item><description>Validates that the courier can handle the delivery distance</description></item>
    ///   <item><description>Creates a new delivery record with the current timestamp</description></item>
    ///   <item><description>Calculates the actual road/walking distance using Google Distance Matrix API</description></item>
    ///   <item><description>Assigns the courier to the delivery</description></item>
    ///   <item><description>Sets TypeShipment based on the courier's vehicle type</description></item>
    ///   <item><description>Updates the order status to DELIVERING</description></item>
    ///   <item><description>Notifies all relevant observers about the changes</description></item>
    /// </list>
    /// The delivery is created with null end status and time, indicating it is in progress.
    /// </remarks>
    public static void Create(DO.Order order, DO.Courier courier)
    {
        s_validateDeliveryDistance(order, courier);

        DO.Delivery delivery = new DO.Delivery
        {
            Id = 0, // Auto-generated by DAL
            OrderId = order.Id,
            CourierId = courier.Id,
            TypeShipment = courier.TypeShipment,
            OrderDate = AdminManager.Now,
            ActualDistance = GoogleMapsService.GetActualDistance(order.Addres, (BO.TheTypeShipment)courier.TypeShipment),
            EndDelivery = null,
            TimeEndDelivery = null
        };

        s_dal.Delivery.Create(delivery);
        s_dal.Order.Update(order with { OrderStatus = DO.OrderStatus.DELIVERING });

        s_notifyAllObservers(delivery.OrderId, courier.Id);
    }

    /// <summary>
    /// Marks a delivery as completed with the specified end status.
    /// </summary>
    /// <param name="courierId">The unique identifier of the courier completing the delivery.</param>
    /// <param name="deliveryId">The unique identifier of the delivery being completed.</param>
    /// <param name="endDelivery">The final status of the delivery attempt.</param>
    /// <exception cref="BO.BlDoesNotExistException">
    /// Thrown when the delivery or associated order does not exist in the system.
    /// </exception>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when the courier attempting to complete the delivery is not the assigned courier.
    /// </exception>
    /// <remarks>
    /// This method performs the following operations:
    /// <list type="number">
    ///   <item><description>Validates that the delivery exists</description></item>
    ///   <item><description>Verifies that the courier is assigned to this delivery</description></item>
    ///   <item><description>Updates the delivery with the end status and completion time</description></item>
    ///   <item><description>Updates the order status based on the delivery outcome</description></item>
    ///   <item><description>Notifies all relevant observers about the changes</description></item>
    /// </list>
    /// 
    /// Order status mapping based on delivery outcome:
    /// <list type="bullet">
    ///   <item><description>DELIVERED → Order COMPLETED</description></item>
    ///   <item><description>CANCELLED → Order CANCELLED</description></item>
    ///   <item><description>REFUSED → Order REFUSED</description></item>
    ///   <item><description>FAILED/NOTFOUND → Order OPEN (available for retry)</description></item>
    /// </list>
    /// </remarks>
    public static void Deliver(int courierId, int deliveryId, BO.EndDelivery endDelivery)
    {
        DO.Delivery delivery = s_getAndValidateDelivery(deliveryId, courierId);

        // Update delivery with completion details
        delivery = delivery with
        {
            EndDelivery = (DO.EndDelivery)endDelivery,
            TimeEndDelivery = AdminManager.Now
        };
        s_dal.Delivery.Update(delivery);

        // Update order status based on delivery outcome
        UpdateOrderStatusAfterDelivery(delivery.OrderId, endDelivery);

        // Notify all observers
        s_notifyDeliveryCompleted(deliveryId, delivery.OrderId, courierId);
    }

    /// <summary>
    /// Validates that the courier can handle the delivery distance.
    /// </summary>
    /// <param name="order">The order to be delivered.</param>
    /// <param name="courier">The courier assigned to the delivery.</param>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when the distance exceeds the courier's maximum capability.
    /// </exception>
    private static void s_validateDeliveryDistance(DO.Order order, DO.Courier courier)
    {
        if (order.DistanceKm > courier.MaxDistanceDelivery)
        {
            throw new BO.BlInvalidValueException(
                $"Courier with ID {courier.Id} cannot deliver to distance {order.DistanceKm} km. " +
                $"Maximum distance: {courier.MaxDistanceDelivery} km");
        }
    }

    /// <summary>
    /// Retrieves and validates a delivery for completion.
    /// </summary>
    /// <param name="deliveryId">The delivery ID to retrieve.</param>
    /// <param name="courierId">The courier ID attempting to complete the delivery.</param>
    /// <returns>The validated delivery object.</returns>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the delivery is not found.</exception>
    /// <exception cref="BO.BlInvalidValueException">Thrown when the courier is not assigned to this delivery.</exception>
    private static DO.Delivery s_getAndValidateDelivery(int deliveryId, int courierId)
    {
        DO.Delivery delivery = s_dal.Delivery.Read(deliveryId)
            ?? throw new BO.BlDoesNotExistException($"Delivery with ID {deliveryId} not found");

        if (delivery.CourierId != courierId)
        {
            throw new BO.BlInvalidValueException(
                $"Courier with ID {courierId} is not assigned to delivery {deliveryId}. " +
                $"Assigned courier: {delivery.CourierId}");
        }

        return delivery;
    }

    /// <summary>
    /// Updates the order status based on the delivery outcome.
    /// </summary>
    /// <param name="orderId">The order ID to update.</param>
    /// <param name="endDelivery">The delivery outcome status.</param>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order is not found.</exception>
    private static void UpdateOrderStatusAfterDelivery(int orderId, BO.EndDelivery endDelivery)
    {
        DO.Order order = s_dal.Order.Read(orderId)
            ?? throw new BO.BlDoesNotExistException($"Order with ID {orderId} not found");

        DO.OrderStatus newStatus = s_mapDeliveryOutcomeToOrderStatus(endDelivery, order.OrderStatus);

        s_dal.Order.Update(order with { OrderStatus = newStatus });
    }

    /// <summary>
    /// Maps a delivery outcome to the corresponding order status.
    /// </summary>
    /// <param name="endDelivery">The delivery outcome.</param>
    /// <param name="currentStatus">The current order status (used as fallback).</param>
    /// <returns>The new order status based on the delivery outcome.</returns>
    private static DO.OrderStatus s_mapDeliveryOutcomeToOrderStatus(
        BO.EndDelivery endDelivery,
        DO.OrderStatus currentStatus)
    {
        return endDelivery switch
        {
            BO.EndDelivery.DELIVERED => DO.OrderStatus.COMPLETED,
            BO.EndDelivery.CANCELLED => DO.OrderStatus.CONCELLED,
            BO.EndDelivery.REFUSED => DO.OrderStatus.REFUSED,
            BO.EndDelivery.FAILED => DO.OrderStatus.OPEN,
            BO.EndDelivery.NOTFOUND => DO.OrderStatus.OPEN,
            _ => currentStatus
        };
    }

    /// <summary>
    /// Notifies all relevant observers after a delivery is created.
    /// </summary>
    /// <param name="orderId">The order ID involved in the delivery.</param>
    /// <param name="courierId">The courier ID assigned to the delivery.</param>
    private static void s_notifyAllObservers(int orderId, int courierId)
    {
        OrderManager.Observer.NotifyItemUpdated(orderId);
        CourierManager.Observer.NotifyItemUpdated(courierId);
        Observer.NotifyListUpdated();
        OrderManager.Observer.NotifyListUpdated();
        CourierManager.Observer.NotifyListUpdated();
    }

    /// <summary>
    /// Notifies all relevant observers after a delivery is completed.
    /// </summary>
    /// <param name="deliveryId">The completed delivery ID.</param>
    /// <param name="orderId">The order ID involved in the delivery.</param>
    /// <param name="courierId">The courier ID who completed the delivery.</param>
    private static void s_notifyDeliveryCompleted(int deliveryId, int orderId, int courierId)
    {
        Observer.NotifyItemUpdated(deliveryId);
        OrderManager.Observer.NotifyItemUpdated(orderId);
        CourierManager.Observer.NotifyItemUpdated(courierId);
        Observer.NotifyListUpdated();
        OrderManager.Observer.NotifyListUpdated();
        CourierManager.Observer.NotifyListUpdated();
    }
}
