using DalApi;


namespace Helpers;

/// <summary>
/// Provides business logic operations for managing orders in the delivery system.
/// </summary>
/// <remarks>
/// This static class handles all order-related operations including creation, retrieval,
/// updates, cancellations, and querying. It serves as an intermediary between the data
/// access layer and the business logic layer, performing necessary conversions and validations.
/// </remarks>
internal static class OrderManager
{
    private static IDal s_dal = Factory.Get; //stage 4

    /// <summary>
    /// Retrieves statistical counts of orders grouped by order status and schedule status.
    /// </summary>
    /// <returns>
    /// An integer array where:
    /// - Indices 0 to maxStatusVal contain counts for each OrderStatus value
    /// - Indices (maxStatusVal + 1) onwards contain counts for each ScheduleStatus value
    /// </returns>
    /// <remarks>
    /// This method groups all orders by their status and schedule status, providing
    /// a comprehensive overview of order distribution across different states.
    /// </remarks>
    public static int[] GetAllOrderStatistic()
    {
        var allOrders = s_dal.Order.ReadAll();
        int maxStatusVal = (int)Enum.GetValues(typeof(BO.OrderStatus)).Cast<BO.OrderStatus>().Max();
        int maxScheduleVal = (int)Enum.GetValues(typeof(BO.ScheduleStatus)).Cast<BO.ScheduleStatus>().Max();

        int[] results = new int[maxStatusVal + 1 + maxScheduleVal + 1];

        var query = (from order in allOrders
                     group order by order.OrderStatus into g
                     select new
                     {
                         Index = (int)g.Key,
                         Count = g.Count()
                     })
                           .Concat
                           (from order in allOrders
                            let timeStatus = Tools.GetScheduleStatus(order)
                            group order by timeStatus into g
                            select new
                            {
                                Index = (int)g.Key + maxStatusVal + 1,
                                Count = g.Count()
                            });

        foreach (var item in query)
        {
            results[item.Index] = item.Count;
        }
        return results;
    }

    /// <summary>
    /// Creates a new order in the system.
    /// </summary>
    /// <param name="boOrder">The business object representing the order to create.</param>
    /// <remarks>
    /// Converts the business logic order object to a data object and persists it.
    /// The order date is automatically set to the current system time.
    /// The order ID is auto-generated by the data layer.
    /// </remarks>
    public static void Create(BO.Order boOrder)
    {
        DO.Order doOrder = new DO.Order
        {
            Id = 0,
            TypeOfOrder = (DO.TypeOfOrder)boOrder.TypeOfOrder,
            Details = boOrder.Details,
            Addres = boOrder.Addres,//חישוב
            Latitude = boOrder.Latitude,
            Longitude = boOrder.Longitude,
            Name = boOrder.Name,
            Phone = boOrder.Phone,//חישוב
            Weight = boOrder.Weight,
            OrderDate = AdminManager.Now,
        };
        s_dal.Order.Create(doOrder);
    }

    /// <summary>
    /// Retrieves all orders from the system with optional filtering and sorting.
    /// </summary>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="filterValue">The value to match for the specified filter field.</param>
    /// <param name="orderBy">The field to sort by (default is OrderStatus).</param>
    /// <returns>A list of orders in list view format, filtered and sorted as specified.</returns>
    /// <remarks>
    /// Converts data layer orders to business logic OrderInList objects,
    /// applies the specified filter predicate, and sorts by the requested field.
    /// </remarks>
    public static List<BO.OrderInList> ReadAll(BO.OrderInListField? filter,
        Object? filterValue,
        BO.OrderInListField? orderBy = BO.OrderInListField.OrderStatus)
    {
        Func<BO.OrderInList, bool> filterPredicate = s_getFilterFunc(filter, filterValue);

        Func<BO.OrderInList, object> sortSelector = s_getSortFunc(orderBy);

        var query = from doOrder in s_dal.Order.ReadAll()
                    let boOrder = s_convertToBoOrderInList(doOrder)
                    where filterPredicate(boOrder)
                    orderby sortSelector(boOrder)
                    select boOrder;
        return [.. query];
    }

    /// <summary>
    /// Retrieves a specific order by its unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the order to retrieve.</param>
    /// <returns>
    /// A business logic Order object with complete details including calculated fields,
    /// or null if no order with the specified ID exists.
    /// </returns>
    /// <remarks>
    /// This method enriches the data layer order with calculated fields such as distance,
    /// estimated delivery time, order status, and associated delivery attempts.
    /// </remarks>
    public static BO.Order? Read(int id)
    {
        var doOrder = s_dal.Order.Read(id);
        if (doOrder is null)
            return null;

        BO.Order boOrder = new BO.Order
        {
            Id = doOrder.Id,
            TypeOfOrder = (BO.TypeOfOrder)doOrder.TypeOfOrder,
            Details = doOrder.Details,
            Latitude = doOrder.Latitude,
            Longitude = doOrder.Longitude,
            Addres = doOrder.Addres,
            Name = doOrder.Name,
            Phone = doOrder.Phone,
            Weight = doOrder.Weight,
            OrderDate = doOrder.OrderDate,
            Distance = Tools.GetDistance(doOrder),
            EstimatedDeliveryTime = Tools.GetEstimatedDeliveryTime(doOrder),
            MaxDeliveryTime = doOrder.OrderDate + AdminManager.GetConfig().MaxDeliveryTime,
            OrderStatus = Tools.GetOrderStatus(doOrder),
            ScheduleStatus = Tools.GetScheduleStatus(doOrder),
            TimeLeftForDelivery = Tools.GetTimeLeftForDelivery(doOrder),
            DeliveryPerOrderInLists = s_createDeliveryPerOrderInList(doOrder.Id)
        };
        return boOrder;
    }

    /// <summary>
    /// Updates an existing order in the system.
    /// </summary>
    /// <param name="boOrder">The business logic order object with updated information.</param>
    /// <exception cref="BO.BlInvalidValueException">Thrown when the phone number is invalid.</exception>
    /// <remarks>
    /// Validates the phone number and updates address coordinates if the address has changed.
    /// If geocoding fails, the existing coordinates are retained.
    /// </remarks>
    public static void Update(BO.Order boOrder)
    {
        if (!Tools.IsValidPhone(boOrder.Phone))
            throw new BO.BlInvalidValueException("Invalid phone number.");

        var adressCoordinates = Tools.GetGeocodingSync(boOrder.Addres);

        DO.Order doOrder = new DO.Order
        {
            Id = boOrder.Id,
            TypeOfOrder = (DO.TypeOfOrder)boOrder.TypeOfOrder,
            Details = boOrder.Details,
            Addres = boOrder.Addres,//חישוב
            Latitude = adressCoordinates?.Lat ?? boOrder.Latitude,
            Longitude = adressCoordinates?.Lng ?? boOrder.Longitude,
            Name = boOrder.Name,
            Phone = boOrder.Phone,
            Weight = boOrder.Weight,
            OrderDate = boOrder.OrderDate,
        };
        s_dal.Order.Update(doOrder);
    }

    /// <summary>
    /// Attempts to delete an order from the system.
    /// </summary>
    /// <param name="id">The unique identifier of the order to delete.</param>
    /// <exception cref="BO.BlDoesNotExistException">Always thrown as orders cannot be deleted.</exception>
    /// <remarks>
    /// Order deletion is not permitted in this system. Orders should be cancelled instead.
    /// </remarks>
    public static void Delete(int id)
    {
        throw new BO.BlDoesNotExistException("Order cannot be deleted");
    }

    /// <summary>
    /// Cancels an existing order based on its current status.
    /// </summary>
    /// <param name="orderId">The unique identifier of the order to cancel.</param>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or associated delivery is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order cannot be cancelled due to its current status.</exception>
    /// <remarks>
    /// Cancellation behavior depends on the order status:
    /// - OPEN/REFUSED: Creates a cancellation delivery record
    /// - DELIVERING: Updates the current delivery with cancellation status
    /// - COMPLETED/CANCELLED: Cannot be cancelled (throws exception)
    /// </remarks>
    public static void Cancel(int orderId)
    {
        DO.Order doOrder = s_dal.Order.Read(orderId)
            ?? throw new BO.BlDoesNotExistException("Order not found");
        Action action = doOrder.OrderStatus switch
        {
            DO.OrderStatus.COMPLETED => throw new BO.BlInvalidOperationException("Cannot cancel a completed order."),
            DO.OrderStatus.CONCELLED => throw new BO.BlInvalidOperationException("Order is already cancelled."),
            DO.OrderStatus.OPEN or DO.OrderStatus.REFUSED => () =>
            {
                doOrder = doOrder with { OrderStatus = DO.OrderStatus.CONCELLED };
                s_dal.Delivery.Create(new DO.Delivery
                {
                    Id = doOrder.Id,
                    OrderId = doOrder.Id,
                    CourierId = 0,
                    TypeShipment = DO.TheTypeShipment.FOOT,
                    OrderDate = AdminManager.Now,
                    EndDelivery = DO.EndDelivery.CONCELLED,
                    TimeEndDelivery = AdminManager.Now,
                    ActualDistance = 0
                });
            }
            ,
            DO.OrderStatus.DELIVERING => () =>
            {
                var delivery = (from d in s_dal.Delivery?.ReadAll()
                                where d.OrderId == doOrder.Id
                                orderby d.Id descending
                                select d).FirstOrDefault()
                                ?? throw new BO.BlDoesNotExistException("Delivery not found for the order");
                s_dal.Delivery?.Update(delivery with
                {
                    EndDelivery = DO.EndDelivery.CONCELLED,
                    TimeEndDelivery = AdminManager.Now
                });
            }
            ,
            _ => throw new BO.BlInvalidOperationException("Invalid order status.")
        };
    }

    /// <summary>
    /// Assigns a courier to an open order, initiating the delivery process.
    /// </summary>
    /// <param name="courierId">The unique identifier of the courier to assign.</param>
    /// <param name="orderId">The unique identifier of the order to assign.</param>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the order or courier is not found.</exception>
    /// <exception cref="BO.BlInvalidOperationException">Thrown when the order is not in OPEN or REFUSED status.</exception>
    /// <remarks>
    /// Creates a new delivery record linking the courier to the order and updates
    /// the order status to DELIVERING. Only orders with OPEN or REFUSED status can be selected.
    /// </remarks>
    public static void StartDelivery(int courierId, int orderId)
    {
        DO.Order doOrder = s_dal.Order.Read(orderId)
            ?? throw new BO.BlDoesNotExistException("Order not found");

        DO.Courier? doCourier = s_dal.Courier.Read(courierId)
            ?? throw new BO.BlDoesNotExistException("Courier not found");

        BO.OrderInList boOrderInList = s_convertToBoOrderInList(doOrder);
        if (boOrderInList.OrderStatus is not (BO.OrderStatus.OPEN or BO.OrderStatus.REFUSED))
            throw new BO.BlInvalidOperationException("Order is not open for selection");

        s_dal.Delivery.Create(new DO.Delivery
        {
            Id = 0,
            OrderId = orderId,
            CourierId = courierId,
            TypeShipment = (DO.TheTypeShipment)doCourier.TypeShipment,
            OrderDate = AdminManager.Now,
        });
        s_dal.Order.Update(doOrder with
        {
            OrderStatus = DO.OrderStatus.DELIVERING
        });
    }

    /// <summary>
    /// Retrieves all completed deliveries for a specific courier with optional filtering and sorting.
    /// </summary>
    /// <param name="courierId">The unique identifier of the courier.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">The field to sort the results by.</param>
    /// <returns>
    /// A list of closed delivery records showing delivery outcomes, distances, times, and final statuses.
    /// Results are filtered to show only one delivery per order (the most recent).
    /// </returns>
    /// <remarks>
    /// Only returns deliveries that have ended (EndDelivery is not null).
    /// Results are deduplicated by OrderId to show only the most recent delivery attempt for each order.
    /// </remarks>
    public static List<BO.ClosedDeliveryInList> GetClosed(int courierId, BO.TypeOfOrder? filter, BO.ClosedDeliveryInListField? sort)
    {
        var query = from doDelivery in s_dal.Delivery.ReadAll(d => d.CourierId == courierId && d.EndDelivery != null)
                    let order = s_dal.Order.Read(doDelivery.OrderId)
                    where order != null && (filter == null || (BO.TypeOfOrder)order.TypeOfOrder == filter)
                    select new BO.ClosedDeliveryInList
                    {
                        DeliveryId = doDelivery.Id,
                        OrderId = order.Id,
                        OrderType = (BO.TypeOfOrder)order.TypeOfOrder,
                        Address = order.Addres,
                        ShipmentType = (BO.TheTypeShipment)doDelivery.TypeShipment,
                        AqualDistens = doDelivery.ActualDistance,
                        DelyveryTime = (TimeSpan)(doDelivery.TimeEndDelivery! - doDelivery.OrderDate),
                        EndDelivery = (BO.EndDelivery)doDelivery.EndDelivery!
                    };
        var uniqueQuery = query.DistinctBy(x => x.OrderId);

        IEnumerable<BO.ClosedDeliveryInList> sortedQuery = sort switch
        {
            BO.ClosedDeliveryInListField.DeliveryId => uniqueQuery.OrderBy(x => x.DeliveryId),
            BO.ClosedDeliveryInListField.OrderId => uniqueQuery.OrderBy(x => x.OrderId),
            BO.ClosedDeliveryInListField.TypeOfOrder => uniqueQuery.OrderBy(x => x.OrderType),
            BO.ClosedDeliveryInListField.Address => uniqueQuery.OrderBy(x => x.Address),
            BO.ClosedDeliveryInListField.ShipmentType => uniqueQuery.OrderBy(x => x.ShipmentType),
            BO.ClosedDeliveryInListField.AqualDistens => uniqueQuery.OrderBy(x => x.AqualDistens),
            BO.ClosedDeliveryInListField.DelyveryTime => uniqueQuery.OrderBy(x => x.DelyveryTime),
            BO.ClosedDeliveryInListField.EndDelivery => uniqueQuery.OrderBy(x => x.EndDelivery),
            _ => uniqueQuery.OrderBy(x => x.OrderType) // ברירת מחדל
        };

        return [.. sortedQuery];
    }

    /// <summary>
    /// Retrieves all open orders available for a specific courier to deliver.
    /// </summary>
    /// <param name="courierId">The unique identifier of the courier.</param>
    /// <param name="filter">Optional filter for order type, or null to include all types.</param>
    /// <param name="sort">The field to sort the results by.</param>
    /// <returns>
    /// A list of open orders within the courier's maximum delivery distance,
    /// including distance calculations, time constraints, and schedule status.
    /// </returns>
    /// <exception cref="BO.BlDoesNotExistException">Thrown when the courier is not found.</exception>
    /// <remarks>
    /// Only returns orders with OPEN or REFUSED status that are within the courier's
    /// maximum delivery distance capability. Results can be filtered by order type and
    /// sorted by various fields.
    /// </remarks>
    public static List<BO.OpenOrderInList> GetOpen(int courierId, BO.TypeOfOrder? filter, BO.OpenOrderInListField? sort)
    {
        DO.Courier doCourier = s_dal.Courier.Read(courierId)
            ?? throw new BO.BlDoesNotExistException("Courier not found");

        var query = from doOrder in s_dal.Order.ReadAll(o => o.OrderStatus == DO.OrderStatus.OPEN || o.OrderStatus == DO.OrderStatus.REFUSED)
                    let distense = Tools.GetDistance(doOrder)
                    where ((filter == null || (BO.TypeOfOrder)doOrder.TypeOfOrder == filter) && (distense <= doCourier.MaxDistanceDelivery))
                    select new BO.OpenOrderInList
                    {
                        OrderId = doOrder.Id,
                        TypeOfOrder = (BO.TypeOfOrder)doOrder.TypeOfOrder,
                        Weight = doOrder.Weight,
                        Address = doOrder.Addres,
                        ActualDistance = null,//לא מחושב עדיין
                        DistanceKm = distense,
                        EstimatedDeliveryTime = null,
                        ScheduleStatus = Tools.GetScheduleStatus(doOrder),
                        TimeLeftForDelivery = Tools.GetTimeLeftForDelivery(doOrder),
                        MaxDeliveryTime = doOrder.OrderDate + AdminManager.GetConfig().MaxDeliveryTime
                    };

        IEnumerable<BO.OpenOrderInList> sortedQuery = sort switch
        {
            BO.OpenOrderInListField.OrderId => query.OrderBy(x => x.OrderId),
            BO.OpenOrderInListField.TypeOfOrder => query.OrderBy(x => x.TypeOfOrder),
            BO.OpenOrderInListField.Weight => query.OrderBy(x => x.Weight),
            BO.OpenOrderInListField.Address => query.OrderBy(x => x.Address),
            BO.OpenOrderInListField.DistanceKm => query.OrderBy(x => x.DistanceKm),
            BO.OpenOrderInListField.ActualDistance => query.OrderBy(x => x.ActualDistance),
            BO.OpenOrderInListField.EstimatedDeliveryTime => query.OrderBy(x => x.EstimatedDeliveryTime),
            BO.OpenOrderInListField.ScheduleStatus => query.OrderBy(x => x.ScheduleStatus),
            BO.OpenOrderInListField.TimeLeftForDelivery => query.OrderBy(x => x.TimeLeftForDelivery),
            BO.OpenOrderInListField.MaxDeliveryTime => query.OrderBy(x => x.MaxDeliveryTime),
            _ => query.OrderBy(x => x.ScheduleStatus) // ברירת מחדל
        };

        return [.. sortedQuery];
    }

    /// <summary>
    /// Converts a data layer order to a business logic OrderInList object.
    /// </summary>
    /// <param name="doOrder">The data layer order to convert.</param>
    /// <returns>
    /// An OrderInList object with calculated fields including status, distance,
    /// timing information, and delivery attempt count.
    /// </returns>
    /// <remarks>
    /// This helper method enriches the order with calculated properties such as
    /// order status (considering the most recent delivery), schedule status,
    /// time remaining, and number of delivery attempts.
    /// </remarks>
    private static BO.OrderInList s_convertToBoOrderInList(DO.Order doOrder)
    {
        DO.Delivery? delivery = (from d in s_dal.Delivery?.ReadAll()
                                 where d.OrderId == doOrder.Id
                                 orderby d.Id descending
                                 select d).FirstOrDefault();

        var orderStatus = Tools.GetOrderStatus(doOrder, delivery);

        return new BO.OrderInList
        {
            DeliveryId = delivery?.Id,
            OrderId = doOrder.Id,
            TypeOfOrder = (BO.TypeOfOrder)doOrder.TypeOfOrder,
            DistanceKm = Tools.GetDistance(doOrder),
            OrderStatus = orderStatus,
            ScheduleStatus = Tools.GetScheduleStatus(doOrder, delivery),
            TimeLeftForDelivery = Tools.GetTimeLeftForDelivery(doOrder, orderStatus),
            TotalTimeOfDelivery = Tools.GetTotalTimeOfDelivery(doOrder, orderStatus, delivery),
            NumberOfDeliveryAttempts = Tools.GetCuntOfDelivery(doOrder.Id)
        };
    }

    /// <summary>
    /// Creates a filter predicate function based on the specified field and value.
    /// </summary>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="filterValue">The value to match against the specified field.</param>
    /// <returns>
    /// A predicate function that returns true if the order matches the filter criteria,
    /// or always returns true if no filter is specified.
    /// </returns>
    /// <exception cref="Exception">Thrown when a filter field is specified but no filter value is provided.</exception>
    /// <remarks>
    /// Supports filtering by OrderId, TypeOfOrder, OrderStatus, DistanceKm, ScheduleStatus,
    /// TimeLeftForDelivery (less than or equal), TotalTimeOfDelivery (less than or equal),
    /// and DeliveryAttempts.
    /// </remarks>
    private static Func<BO.OrderInList, bool> s_getFilterFunc(BO.OrderInListField? filter, Object? filterValue)
    {
        if (filter is not null && filterValue is null)
            throw new Exception("not send value for filter");
        return filter switch
        {
            BO.OrderInListField.OrderId => (o) => o.OrderId == (int)filterValue!,
            BO.OrderInListField.TypeOfOrder => (o) => o.TypeOfOrder == (BO.TypeOfOrder)filterValue!,
            BO.OrderInListField.OrderStatus => (o) => o.OrderStatus == (BO.OrderStatus)filterValue!,
            BO.OrderInListField.DistanceKm => (o) => o.DistanceKm == (double)filterValue!,
            BO.OrderInListField.ScheduleStatus => (o) => o.ScheduleStatus == (BO.ScheduleStatus)filterValue!,
            BO.OrderInListField.TimeLeftForDelivery => (o) => o.TimeLeftForDelivery <= (TimeSpan)filterValue!,
            BO.OrderInListField.TotalTimeOfDelivery => (o) => o.TotalTimeOfDelivery <= (TimeSpan)filterValue!,
            BO.OrderInListField.DeliveryAttempts => (o) => o.NumberOfDeliveryAttempts == (int)filterValue!,
            _ => (o) => true
        };
    }

    /// <summary>
    /// Creates a sort selector function based on the specified field.
    /// </summary>
    /// <param name="sort">The field to sort by, or null to use default sorting.</param>
    /// <returns>
    /// A selector function that extracts the specified field value from an OrderInList object,
    /// or extracts OrderStatus if no sort field is specified.
    /// </returns>
    /// <remarks>
    /// Supports sorting by OrderId, TypeOfOrder, OrderStatus, DistanceKm, ScheduleStatus,
    /// TimeLeftForDelivery, and TotalTimeOfDelivery. Default sort is by OrderStatus.
    /// </remarks>
    private static Func<BO.OrderInList, Object> s_getSortFunc(BO.OrderInListField? sort)
    {
        return sort switch
        {
            BO.OrderInListField.OrderId => (o) => o.OrderId,
            BO.OrderInListField.TypeOfOrder => (o) => o.TypeOfOrder,
            BO.OrderInListField.OrderStatus => (o) => o.OrderStatus,
            BO.OrderInListField.DistanceKm => (o) => o.DistanceKm,
            BO.OrderInListField.ScheduleStatus => (o) => o.ScheduleStatus,
            BO.OrderInListField.TimeLeftForDelivery => (o) => o.TimeLeftForDelivery,
            BO.OrderInListField.TotalTimeOfDelivery => (o) => o.TotalTimeOfDelivery,
            _ => (o) => o.OrderStatus
        };
    }

    /// <summary>
    /// Creates a list of all delivery attempts associated with a specific order.
    /// </summary>
    /// <param name="orderId">The unique identifier of the order.</param>
    /// <returns>
    /// A list of DeliveryPerOrderInList objects containing details about each delivery attempt,
    /// or null if no deliveries have been attempted for this order.
    /// </returns>
    /// <remarks>
    /// Each delivery record includes the assigned courier information, shipment type,
    /// timing details, and outcome status. This provides a complete history of all
    /// delivery attempts for the order.
    /// </remarks>
    private static List<BO.DeliveryPerOrderInList>? s_createDeliveryPerOrderInList(int orderId)
    {
        var deliveries = from doDelivery in s_dal.Delivery.ReadAll(d => d.OrderId == orderId)
                         let courier = s_dal.Courier.Read(doDelivery.CourierId)
                         select new BO.DeliveryPerOrderInList
                         {
                             DeliveryId = doDelivery.Id,
                             CourierId = courier.Id,
                             CourierName = courier.Name,
                             TypeShipment = (BO.TheTypeShipment)courier.TypeShipment,
                             OrderDate = doDelivery.OrderDate,
                             EndDelivery = doDelivery.EndDelivery.HasValue ? (BO.EndDelivery)doDelivery.EndDelivery.Value : null,
                             TimeEndDelivery = doDelivery.TimeEndDelivery.HasValue ? doDelivery.TimeEndDelivery.Value : null
                         }
        ;
        return deliveries.Any() ? [.. deliveries] : null;
    }

}

