using BO;
using DalApi;
using System.Net.Mail;
using System.Threading.Tasks;

namespace Helpers;

/// <summary>
/// Provides business logic operations for managing orders in the delivery system.
/// </summary>
/// <remarks>
/// This static class handles all order-related operations including creation, retrieval,
/// updates, cancellations, and querying. It serves as an intermediary between the data
/// access layer and the business logic layer, performing necessary conversions and validations.
/// </remarks>
internal static class OrderManager
{
    /// <summary>
    /// Data access layer instance for database operations.
    /// </summary>
    private static readonly IDal s_dal = Factory.Get;

    /// <summary>
    /// Observer manager for notifying UI components about order changes.
    /// </summary>
    internal static readonly ObserverManager Observer = new();

    /// <summary>
    /// Retrieves statistical counts of orders grouped by order status and schedule status.
    /// </summary>
    /// <returns>
    /// An integer array where:
    /// <list type="bullet">
    ///   <item><description>Indices 0 to maxStatusVal contain counts for each OrderStatus value</description></item>
    ///   <item><description>Indices (maxStatusVal + 1) onwards contain counts for each ScheduleStatus value</description></item>
    /// </list>
    /// </returns>
    /// <remarks>
    /// This method groups all orders by their status and schedule status, providing
    /// a comprehensive overview of order distribution across different states.
    /// </remarks>
    public static async Task<int[]> GetAllOrderStatistic()
    {
        var allOrders = s_dal.Order.ReadAll().ToList();

        int maxStatusVal = (int)Enum.GetValues(typeof(BO.OrderStatus)).Cast<BO.OrderStatus>().Max();
        int maxScheduleVal = (int)Enum.GetValues(typeof(BO.ScheduleStatus)).Cast<BO.ScheduleStatus>().Max();

        int[] results = new int[maxStatusVal + 1 + maxScheduleVal + 1];

        var statusGroups = allOrders
            .GroupBy(o => o.OrderStatus)
            .Select(g => new { Index = (int)g.Key, Count = g.Count() });

        foreach (var item in statusGroups)
        {
            results[item.Index] = item.Count;
        }

        var scheduleTasks = allOrders.Select(async o => await Tools.GetScheduleStatus(o));

        var scheduleResults = await Task.WhenAll(scheduleTasks);
        var scheduleGroups = scheduleResults
            .GroupBy(s => s)
            .Select(g => new { Index = (int)g.Key + maxStatusVal + 1, Count = g.Count() });

        foreach (var item in scheduleGroups)
        {
            results[item.Index] = item.Count;
        }

        return results;
    }

    /// <summary>
    /// Creates a new order in the system.
    /// </summary>
    /// <param name="boOrder">The business object representing the order to create.</param>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when order details, address, name, or phone number are invalid or empty,
    /// or when geocoding the address fails.
    /// </exception>
    /// <exception cref="BO.BlInvalidOperationException">
    /// Thrown when the delivery distance exceeds the maximum allowed range.
    /// </exception>
    /// <remarks>
    /// <para>Validates all required fields and geocodes the delivery address before creation.</para>
    /// <para>The order date is automatically set to the current system time.</para>
    /// <para>The order ID is auto-generated by the data layer.</para>
    /// </remarks>
    public static async Task Create(BO.Order boOrder)
    {
        s_validateOrderFields(boOrder);

        var addressCoordinates = await GoogleMapsService.GetGeocodingAsync(boOrder.Addres);

        var distance = Tools.GetDistance(
            addressCoordinates?.Lat ?? 0,
            addressCoordinates?.Lng ?? 0,
            s_dal.Config.Latitude ?? 0,
            s_dal.Config.Longitude ?? 0);

        if (distance == 0 || distance > s_dal.Config.MaxDeliveryRange)
            throw new BO.BlInvalidOperationException(
                $"The distance {distance} KM exceeds the delivery range {s_dal.Config.MaxDeliveryRange} KM");

        DO.Order doOrder = new DO.Order
        {
            Id = 0,
            TypeOfOrder = (DO.TypeOfOrder)boOrder.TypeOfOrder,
            Details = boOrder.Details,
            Addres = boOrder.Addres,
            Latitude = addressCoordinates?.Lat ?? throw new BO.BlInvalidValueException("Failed to geocode address."),
            Longitude = addressCoordinates?.Lng ?? throw new BO.BlInvalidValueException("Failed to geocode address."),
            Name = boOrder.Name,
            Phone = boOrder.Phone,
            Weight = boOrder.Weight,
            OrderDate = AdminManager.Now,
            DistanceKm = distance,
        };

        s_dal.Order.Create(doOrder);
        Observer.NotifyListUpdated();
    }

    /// <summary>
    /// Retrieves a specific order by its unique identifier.
    /// </summary>
    /// <param name="id">The unique identifier of the order to retrieve.</param>
    /// <returns>
    /// A business logic Order object with complete details including calculated fields,
    /// or null if no order with the specified ID exists.
    /// </returns>
    /// <remarks>
    /// This method enriches the data layer order with calculated fields such as distance,
    /// estimated delivery time, order status, and associated delivery attempts.
    /// </remarks>
    public static async Task<BO.Order?> Read(int id)
    {
        var doOrder = s_dal.Order.Read(id);
        if (doOrder is null)
            return null;

        var deliveryPerOrderInLists = s_createDeliveryPerOrderInList(doOrder.Id);
        DateTime? estimatedDeliveryTime = await s_calculateEstimatedDeliveryTime(doOrder, deliveryPerOrderInLists);

        return new BO.Order
        {
            Id = doOrder.Id,
            TypeOfOrder = (BO.TypeOfOrder)doOrder.TypeOfOrder,
            Details = doOrder.Details,
            Latitude = doOrder.Latitude,
            Longitude = doOrder.Longitude,
            Addres = doOrder.Addres,
            Name = doOrder.Name,
            Phone = doOrder.Phone,
            Weight = doOrder.Weight,
            OrderDate = doOrder.OrderDate,
            Distance = Tools.GetDistance(doOrder),
            EstimatedDeliveryTime = estimatedDeliveryTime,
            MaxDeliveryTime = doOrder.OrderDate + AdminManager.GetConfig().MaxDeliveryTime,
            OrderStatus = (BO.OrderStatus)doOrder.OrderStatus,
            ScheduleStatus = await Tools.GetScheduleStatus(doOrder),
            TimeLeftForDelivery = Tools.GetTimeLeftForDelivery(doOrder),
            DeliveryPerOrderInLists = deliveryPerOrderInLists
        };
    }

    /// <summary>
    /// Updates an existing order in the system.
    /// </summary>
    /// <param name="boOrder">The business logic order object with updated information.</param>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when order details, address, name, or phone number are invalid or empty,
    /// or when geocoding the address fails.
    /// </exception>
    /// <remarks>
    /// Validates all required fields including phone number and updates address coordinates
    /// by geocoding the address. If geocoding fails, an exception is thrown.
    /// </remarks>
    public static async Task Update(BO.Order boOrder)
    {
        s_validateOrderFields(boOrder);

        var addressCoordinates = await GoogleMapsService.GetGeocodingAsync(boOrder.Addres);

        DO.Order doOrder = new DO.Order
        {
            Id = boOrder.Id,
            TypeOfOrder = (DO.TypeOfOrder)boOrder.TypeOfOrder,
            Details = boOrder.Details,
            Addres = boOrder.Addres,
            Latitude = addressCoordinates?.Lat ?? throw new BO.BlInvalidValueException("Failed to geocode address."),
            Longitude = addressCoordinates?.Lng ?? throw new BO.BlInvalidValueException("Failed to geocode address."),
            Name = boOrder.Name,
            Phone = boOrder.Phone,
            Weight = boOrder.Weight,
            OrderDate = boOrder.OrderDate,
        };

        s_dal.Order.Update(doOrder);
        Observer.NotifyItemUpdated(boOrder.Id);
        Observer.NotifyListUpdated();
    }

    /// <summary>
    /// Attempts to delete an order from the system.
    /// </summary>
    /// <param name="id">The unique identifier of the order to delete.</param>
    /// <exception cref="BO.BlInvalidOperationException">Always thrown as orders cannot be deleted.</exception>
    /// <remarks>
    /// Order deletion is not permitted in this system. Orders should be cancelled instead
    /// using the <see cref="Cancel(int)"/> method.
    /// </remarks>
    public static void Delete(int id)
    {
        throw new BO.BlInvalidOperationException("Order cannot be deleted. Use Cancel instead.");
    }

    /// <summary>
    /// Retrieves all orders from the system with optional filtering and sorting.
    /// </summary>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="filterValue">The value to match for the specified filter field.</param>
    /// <param name="orderBy">The field to sort by (default is OrderStatus).</param>
    /// <returns>A list of orders in list view format, filtered and sorted as specified.</returns>
    /// <remarks>
    /// Converts data layer orders to business logic OrderInList objects,
    /// applies the specified filter predicate, and sorts by the requested field.
    /// </remarks>
    public static async Task<List<BO.OrderInList>> ReadAll(
        BO.OrderInListField? filter,
        object? filterValue,
        BO.OrderInListField? orderBy = BO.OrderInListField.OrderStatus)
    {
        Func<BO.OrderInList, bool> filterPredicate = s_getFilterPredicate(filter, filterValue);
        return await ReadAll(filterPredicate, orderBy);
    }

    /// <summary>
    /// Retrieves all orders from the system with a custom filter predicate.
    /// </summary>
    /// <param name="customPredicate">Custom filter function, or null to include all orders.</param>
    /// <param name="orderBy">The field to sort by (default is OrderId).</param>
    /// <returns>A list of orders in list view format, filtered and sorted as specified.</returns>
    public static async Task<List<BO.OrderInList>> ReadAll(
        Func<BO.OrderInList, bool>? customPredicate = null,
        BO.OrderInListField? orderBy = BO.OrderInListField.OrderId)
    {
        var deliveriesMap = s_dal.Delivery.ReadAll()
            .GroupBy(d => d.OrderId)
            .ToDictionary(g => g.Key, g => g.OrderByDescending(d => d.Id).ToList());

        Func<BO.OrderInList, bool> filter = customPredicate ?? (_ => true);
        Func<BO.OrderInList, object> sortSelector = s_getSortSelector(orderBy);

        var conversionTasks = s_dal.Order.ReadAll().Select(async doOrder =>
        {
            return await s_convertToBoOrderOptimized(doOrder, deliveriesMap);
        });

        var allBoOrders = await Task.WhenAll(conversionTasks);
        var result = allBoOrders
            .Where(filter)
            .OrderBy(sortSelector);

        return [.. result];
    }


    /// <summary>
    /// Cancels an existing order based on its current status.
    /// </summary>
    /// <param name="orderId">The unique identifier of the order to cancel.</param>
    /// <exception cref="BO.BlDoesNotExistException">
    /// Thrown when the order or associated delivery is not found.
    /// </exception>
    /// <exception cref="BO.BlInvalidOperationException">
    /// Thrown when the order cannot be cancelled due to its current status.
    /// </exception>
    /// <remarks>
    /// Cancellation behavior depends on the order status:
    /// <list type="bullet">
    ///   <item><description>OPEN/REFUSED: Creates a cancellation delivery record</description></item>
    ///   <item><description>DELIVERING: Updates the current delivery with cancellation status and notifies courier via email</description></item>
    ///   <item><description>COMPLETED/CANCELLED: Cannot be cancelled (throws exception)</description></item>
    /// </list>
    /// </remarks>
    public static async Task Cancel(int orderId, bool token = false)
    {
        DO.Order doOrder = s_dal.Order.Read(orderId)
            ?? throw new BO.BlDoesNotExistException("הזמנה לא נמצאה לביטול");

        switch (doOrder.OrderStatus)
        {
            case DO.OrderStatus.COMPLETED:
                throw new BO.BlInvalidOperationException("לא ניתן לבטל הזמנה שנמסרה.");

            case DO.OrderStatus.CONCELLED:
                throw new BO.BlInvalidOperationException("לא ניתן לבטל, ההזמנה בוטלה בעבר.");

            case DO.OrderStatus.OPEN:

            case DO.OrderStatus.REFUSED:
                s_cancelOpenOrder(doOrder);
                break;

            case DO.OrderStatus.DELIVERING:
                await s_cancelDeliveringOrder(doOrder, orderId, token);
                break;

            default:
                throw new BO.BlInvalidOperationException("Invalid order status.");
        }



        Observer.NotifyItemUpdated(orderId);
        Observer.NotifyListUpdated();
    }

    /// <summary>
    /// Validates all required fields of an order.
    /// </summary>
    /// <param name="order">The order to validate.</param>
    /// <exception cref="BO.BlInvalidValueException">Thrown when any required field is invalid.</exception>
    private static void s_validateOrderFields(BO.Order order)
    {
        if (string.IsNullOrEmpty(order.Name))
            throw new BO.BlInvalidValueException("Order name cannot be empty.");

        if (!Tools.IsValidPhone(order.Phone))
            throw new BO.BlInvalidValueException("Invalid phone number.");

        if (string.IsNullOrEmpty(order.Addres))
            throw new BO.BlInvalidValueException("Order address cannot be empty.");

        if (string.IsNullOrEmpty(order.Details))
            throw new BO.BlInvalidValueException("Order details cannot be empty.");
    }

    /// <summary>
    /// Converts a data layer order to a business logic OrderInList object using pre-fetched deliveries.
    /// </summary>
    /// <param name="doOrder">The data layer order to convert.</param>
    /// <param name="deliveriesMap">Pre-fetched deliveries grouped by order ID.</param>
    /// <returns>An OrderInList object with calculated fields.</returns>
    private static async Task<BO.OrderInList> s_convertToBoOrderOptimized(
        DO.Order doOrder,
        Dictionary<int, List<DO.Delivery>> deliveriesMap)
    {
        List<DO.Delivery> orderDeliveries = deliveriesMap.TryGetValue(doOrder.Id, out var deliveries)
            ? deliveries
            : [];

        DO.Delivery? latestDelivery = orderDeliveries.FirstOrDefault();
        var orderStatus = (BO.OrderStatus)doOrder.OrderStatus;
        double distanceKm = doOrder.DistanceKm ?? Tools.GetDistance(doOrder);

        return new BO.OrderInList
        {
            OrderId = doOrder.Id,
            DeliveryId = latestDelivery?.Id,
            TypeOfOrder = (BO.TypeOfOrder)doOrder.TypeOfOrder,
            DistanceKm = distanceKm,
            OrderStatus = orderStatus,
            ScheduleStatus = await Tools.GetScheduleStatus(doOrder, latestDelivery),
            TimeLeftForDelivery = Tools.GetTimeLeftForDelivery(doOrder, orderStatus),
            TotalTimeOfDelivery = Tools.GetTotalTimeOfDelivery(doOrder, orderStatus, latestDelivery?.TimeEndDelivery),
            NumberOfDeliveryAttempts = orderDeliveries.Count
        };
    }

    /// <summary>
    /// Creates a list of all delivery attempts associated with a specific order.
    /// </summary>
    /// <param name="orderId">The unique identifier of the order.</param>
    /// <returns>
    /// A list of DeliveryPerOrderInList objects, or null if no deliveries exist.
    /// </returns>
    private static List<BO.DeliveryPerOrderInList>? s_createDeliveryPerOrderInList(int orderId)
    {
        var deliveries = from doDelivery in s_dal.Delivery.ReadAll(d => d.OrderId == orderId)
                         let courier = s_dal.Courier.Read(doDelivery.CourierId)
                         select new BO.DeliveryPerOrderInList
                         {
                             DeliveryId = doDelivery.Id,
                             CourierId = courier.Id,
                             CourierName = courier.Name,
                             TypeShipment = (BO.TheTypeShipment)courier.TypeShipment,
                             OrderDate = doDelivery.OrderDate,
                             EndDelivery = doDelivery.EndDelivery.HasValue
                                 ? (BO.EndDelivery)doDelivery.EndDelivery.Value
                                 : null,
                             TimeEndDelivery = doDelivery.TimeEndDelivery
                         };

        return deliveries.Any() ? [.. deliveries] : null;
    }

    /// <summary>
    /// Calculates the estimated delivery time for an order.
    /// </summary>
    /// <param name="doOrder">The data layer order.</param>
    /// <param name="deliveries">List of delivery attempts for the order.</param>
    /// <returns>The estimated delivery time, or null if not applicable.</returns>
    private static async Task<DateTime?> s_calculateEstimatedDeliveryTime(
        DO.Order doOrder,
        List<BO.DeliveryPerOrderInList>? deliveries)
    {
        if (deliveries is not List<BO.DeliveryPerOrderInList> orderInProgresses)
            return null;

        var activeDelivery = orderInProgresses
            .OrderByDescending(d => d.DeliveryId)
            .FirstOrDefault(d => d.EndDelivery == null);

        return activeDelivery != null
            ? activeDelivery.OrderDate + await Tools.GetEstimatedDeliveryTime(doOrder)
            : null;
    }

    /// <summary>
    /// Cancels an order that is in OPEN or REFUSED status.
    /// </summary>
    /// <param name="doOrder">The order to cancel.</param>
    private static void s_cancelOpenOrder(DO.Order doOrder)
    {
        doOrder = doOrder with { OrderStatus = DO.OrderStatus.CONCELLED };
        s_dal.Order.Update(doOrder);
        Observer.NotifyItemUpdated(doOrder.Id);

        DO.Delivery delivery = new DO.Delivery
        {
            Id = 0,
            OrderId = doOrder.Id,
            CourierId = 0,
            TypeShipment = DO.TheTypeShipment.FOOT,
            OrderDate = AdminManager.Now,
            EndDelivery = DO.EndDelivery.CONCELLED,
            TimeEndDelivery = AdminManager.Now,
            ActualDistance = 0
        };
        s_dal.Delivery.Create(delivery);
    }

    /// <summary>
    /// Cancels an order that is currently being delivered.
    /// </summary>
    /// <param name="doOrder">The order to cancel.</param>
    /// <param name="orderId">The order ID for notification purposes.</param>
    /// <exception cref="BO.BlDoesNotExistException">
    /// Thrown when the delivery or courier is not found.
    /// </exception>
    private static async Task s_cancelDeliveringOrder(DO.Order doOrder, int orderId, bool token)
    {
        doOrder = doOrder with { OrderStatus = DO.OrderStatus.CONCELLED };
        s_dal.Order.Update(doOrder);
        Observer.NotifyItemUpdated(doOrder.Id);

        var delivery = (from d in s_dal.Delivery.ReadAll()
                        where d.OrderId == doOrder.Id
                        orderby d.Id descending
                        select d).FirstOrDefault()
            ?? throw new BO.BlDoesNotExistException("לא נמצא משלוח עבור הזמנה זו");

        s_dal.Delivery.Update(delivery with
        {
            EndDelivery = DO.EndDelivery.CONCELLED,
            TimeEndDelivery = AdminManager.Now
        });

        var courier = s_dal.Courier.Read(delivery.CourierId)
            ?? throw new BO.BlDoesNotExistException("Courier not found");

        Exception? exceptionMail = null;
        Exception? exceptionSms = null;
        try
        {
            await Tools.SendEmailSkript(
                  courier.Email,
                  $"{courier.Name}, ההזמנה בוטלה!!!",
                  $"הזמנה מספר {orderId} בוטלה על ידי המנהל.");

        }

        catch (BLNoSendEmailException ex)
        {
            exceptionMail = new BLNoSendEmailException($"Failed to send email notification {ex.Message}");
        }

        try
        {
            if (token)
            {
                await Tools.SendSms(
                      courier.Phone,
                      $"{courier.Name}, ההזמנה בוטלה!!!",
                      $"Order number {orderId} has been cancelled by the manager");
            }
        }
        catch (BLNoSendSmsException)
        {
            exceptionSms = new BLNoSendSmsException("Failed to send sms notification");
        }
        try
        {
            if (exceptionMail is not null && exceptionSms is not null)
                throw new BLNoSendSmsException($"לא נשלחה הודעה כלל למוביל, {exceptionSms} {exceptionMail}");
        }



        finally
        {
            DeliveryManager.Observer.NotifyItemUpdated(delivery.Id);
            CourierManager.Observer.NotifyItemUpdated(delivery.CourierId);
            Observer.NotifyItemUpdated(orderId);
            Observer.NotifyListUpdated();
        }
    }

    /// <summary>
    /// Creates a filter predicate function based on the specified field and value.
    /// </summary>
    /// <param name="filter">The field to filter by, or null for no filtering.</param>
    /// <param name="filterValue">The value to match against the specified field.</param>
    /// <returns>A predicate function for filtering orders.</returns>
    /// <exception cref="BO.BlInvalidValueException">
    /// Thrown when a filter field is specified but no filter value is provided.
    /// </exception>
    private static Func<BO.OrderInList, bool> s_getFilterPredicate(
        BO.OrderInListField? filter,
        object? filterValue)
    {
        if (filter is not null && filterValue is null)
            throw new BO.BlInvalidValueException("Filter value must be provided when a filter field is specified.");

        return filter switch
        {
            BO.OrderInListField.OrderId => o => o.OrderId == (int)filterValue!,
            BO.OrderInListField.TypeOfOrder => o => o.TypeOfOrder == (BO.TypeOfOrder)filterValue!,
            BO.OrderInListField.OrderStatus => o => o.OrderStatus == (BO.OrderStatus)filterValue!,
            BO.OrderInListField.DistanceKm => o => o.DistanceKm == Convert.ToDouble(filterValue),
            BO.OrderInListField.ScheduleStatus => o => o.ScheduleStatus == (BO.ScheduleStatus)filterValue!,
            BO.OrderInListField.TimeLeftForDelivery => o => o.TimeLeftForDelivery <= (TimeSpan)filterValue!,
            BO.OrderInListField.TotalTimeOfDelivery => o => o.TotalTimeOfDelivery <= (TimeSpan)filterValue!,
            BO.OrderInListField.DeliveryAttempts => o => o.NumberOfDeliveryAttempts == (int)filterValue!,
            _ => _ => true
        };
    }

    /// <summary>
    /// Creates a sort selector function based on the specified field.
    /// </summary>
    /// <param name="sort">The field to sort by, or null to use default sorting.</param>
    /// <returns>A selector function that extracts the specified field value.</returns>
    private static Func<BO.OrderInList, object> s_getSortSelector(BO.OrderInListField? sort)
    {
        return sort switch
        {
            BO.OrderInListField.OrderId => o => o.OrderId,
            BO.OrderInListField.TypeOfOrder => o => o.TypeOfOrder,
            BO.OrderInListField.OrderStatus => o => o.OrderStatus,
            BO.OrderInListField.DistanceKm => o => o.DistanceKm,
            BO.OrderInListField.ScheduleStatus => o => o.ScheduleStatus,
            BO.OrderInListField.TimeLeftForDelivery => o => o.TimeLeftForDelivery,
            BO.OrderInListField.TotalTimeOfDelivery => o => o.TotalTimeOfDelivery,
            _ => o => o.OrderStatus
        };
    }

}

